/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Pictures/pictures';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import9 from '../../../app/services/services';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/core/src/security';
export class Wrapper_Pictures {
  /*private*/ _eventHandler:Function;
  context:import0.Pictures;
  /*private*/ _changed:boolean;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.Pictures(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.headImageUpdate.subscribe(_eventHandler.bind(view,'headImageUpdate'))); }
  }
}
var renderType_Pictures_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Pictures_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Pictures>;
  _Pictures_0_3:Wrapper_Pictures;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Pictures_Host0,renderType_Pictures_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Pictures0(this.viewUtils,this,0,this._el_0);
    this._Pictures_0_3 = new Wrapper_Pictures(this.injectorGet(import8.DomSanitizer,this.parentIndex),this.injectorGet(import9.DataService,this.parentIndex),this.injectorGet(import9.CacheManager,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex),this.injector(0));
    this.compView_0.create(this._Pictures_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Pictures_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Pictures) && (0 === requestNodeIndex))) { return this._Pictures_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Pictures_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Pictures_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._Pictures_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PicturesNgFactory:import7.ComponentFactory<import0.Pictures> = new import7.ComponentFactory<import0.Pictures>('ng-component',View_Pictures_Host0,import0.Pictures);
const styles_Pictures:any[] = ([] as any[]);
var renderType_Pictures:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_Pictures,{});
export class View_Pictures0 extends import1.AppView<import0.Pictures> {
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import11.ViewContainer;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import12.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import11.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import13.Wrapper_NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import11.ViewContainer;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import13.Wrapper_NgIf;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _vc_30:import11.ViewContainer;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import13.Wrapper_NgIf;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _vc_32:import11.ViewContainer;
  _TemplateRef_32_5:any;
  _NgIf_32_6:import13.Wrapper_NgIf;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _vc_37:import11.ViewContainer;
  _TemplateRef_37_5:any;
  _NgFor_37_6:import12.Wrapper_NgFor;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_59:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Pictures0,renderType_Pictures,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_59 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','swiper-container hidden-lg hidden-md hidden-sm'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','swiper-wrapper'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_7 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_8 = new import11.ViewContainer(8,5,this,this._anchor_8);
    this._TemplateRef_8_5 = new import15.TemplateRef_(this,8,this._anchor_8);
    this._NgFor_8_6 = new import12.Wrapper_NgFor(this._vc_8.vcRef,this._TemplateRef_8_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_9 = this.renderer.createText(this._el_5,'\n\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','swiper-button-prev'),(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','swiper-button-next'),(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n\n\n',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','black-panel hidden-xs','id',''),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','outer-image-div'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._vc_23 = new import11.ViewContainer(23,21,this,this._anchor_23);
    this._TemplateRef_23_5 = new import15.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import13.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._vc_25 = new import11.ViewContainer(25,21,this,this._anchor_25);
    this._TemplateRef_25_5 = new import15.TemplateRef_(this,25,this._anchor_25);
    this._NgIf_25_6 = new import13.Wrapper_NgIf(this._vc_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-10   text-center main-image'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._vc_30 = new import11.ViewContainer(30,21,this,this._anchor_30);
    this._TemplateRef_30_5 = new import15.TemplateRef_(this,30,this._anchor_30);
    this._NgIf_30_6 = new import13.Wrapper_NgIf(this._vc_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._vc_32 = new import11.ViewContainer(32,21,this,this._anchor_32);
    this._TemplateRef_32_5 = new import15.TemplateRef_(this,32,this._anchor_32);
    this._NgIf_32_6 = new import13.Wrapper_NgIf(this._vc_32.vcRef,this._TemplateRef_32_5);
    this._text_33 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','tool-strip '),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_35,(null as any));
    this._vc_37 = new import11.ViewContainer(37,35,this,this._anchor_37);
    this._TemplateRef_37_5 = new import15.TemplateRef_(this,37,this._anchor_37);
    this._NgFor_37_6 = new import12.Wrapper_NgFor(this._vc_37.vcRef,this._TemplateRef_37_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_38 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_19,'\n\n',(null as any));
    this._text_40 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import17.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import15.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import18.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import15.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import18.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import15.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import18.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6.context; }
    if (((token === import15.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import18.NgIf) && (32 === requestNodeIndex))) { return this._NgIf_32_6.context; }
    if (((token === import15.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import17.NgFor) && (37 === requestNodeIndex))) { return this._NgFor_37_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.context.images;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_23_0_0:any = this.context.isEnglish;
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    const currVal_25_0_0:any = this.context.isHebrew;
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    const currVal_30_0_0:any = this.context.isEnglish;
    this._NgIf_30_6.check_ngIf(currVal_30_0_0,throwOnChange,false);
    this._NgIf_30_6.ngDoCheck(this,this._anchor_30,throwOnChange);
    const currVal_32_0_0:any = this.context.isHebrew;
    this._NgIf_32_6.check_ngIf(currVal_32_0_0,throwOnChange,false);
    this._NgIf_32_6.ngDoCheck(this,this._anchor_32,throwOnChange);
    const currVal_37_0_0:any = this.context.images;
    this._NgFor_37_6.check_ngForOf(currVal_37_0_0,throwOnChange,false);
    this._NgFor_37_6.ngDoCheck(this,this._anchor_37,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    this._vc_30.detectChangesInNestedViews(throwOnChange);
    this._vc_32.detectChangesInNestedViews(throwOnChange);
    this._vc_37.detectChangesInNestedViews(throwOnChange);
    const currVal_59:any = this.context.mainImagePath;
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementStyle(this._el_27,'background-image',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_59) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_59).toString()));
      this._expr_59 = currVal_59;
    }
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._vc_30.destroyNestedViews();
    this._vc_32.destroyNestedViews();
    this._vc_37.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 8)) { return new View_Pictures1(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 23)) { return new View_Pictures2(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 25)) { return new View_Pictures3(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    if ((nodeIndex == 30)) { return new View_Pictures4(this.viewUtils,this,30,this._anchor_30,this._vc_30); }
    if ((nodeIndex == 32)) { return new View_Pictures5(this.viewUtils,this,32,this._anchor_32,this._vc_32); }
    if ((nodeIndex == 37)) { return new View_Pictures6(this.viewUtils,this,37,this._anchor_37,this._vc_37); }
    return (null as any);
  }
}
class View_Pictures1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures1,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import14.UNINITIALIZED;
    this._expr_5 = import14.UNINITIALIZED;
    this._expr_6 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','swiper-slide'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray4(4,'class','img-responsive swiper-slide','height','100'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = this.context.$implicit.ID;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'id',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.$implicit.ImageURL;
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.parentView.context.isSelected(this.context.$implicit);
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'thumbnail-selected',currVal_6);
      this._expr_6 = currVal_6;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onSelectedImage(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures2,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','left-filler  col-sm-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-hand-left switch-image-glyphicon left-arrow'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = (this.parentView.context.mainImagePath == (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onLeft()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures3,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','right-filler   col-sm-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-hand-right switch-image-glyphicon right-arrow'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onRight()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures4,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','right-filler  col-sm-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-hand-right switch-image-glyphicon right-arrow float-right'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onRight()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures5,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','left-filler   col-sm-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon float-left glyphicon-hand-left switch-image-glyphicon left-arrow'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = (this.parentView.context.mainImagePath == (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onLeft()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_Pictures6,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this._expr_3 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray4(4,'class','img-thumbnail','height','100'),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit.ID;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.$implicit.ImageURL;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.parentView.context.isSelected(this.context.$implicit);
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'thumbnail-selected',currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onSelectedImage(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}