/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['img[_ngcontent-%COMP%] {\r\n    margin: 0 auto;\r\n}'];
//# sourceMappingURL=pictures.css.shim.ngstyle.js.map