/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Pictures/pictures';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import9 from '../../../app/services/services';
import * as import10 from '@angular/router/src/router';
import * as import11 from './pictures.css.shim.ngstyle';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '../../../app/pipes/pipes';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '@angular/core/src/change_detection/change_detection_util';
import * as import19 from '@angular/core/src/security';
import * as import20 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import21 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/common/src/directives/ng_class';
export class Wrapper_Pictures {
  /*private*/ _eventHandler:Function;
  context:import0.Pictures;
  /*private*/ _changed:boolean;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.Pictures(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.headImageUpdate.subscribe(_eventHandler.bind(view,'headImageUpdate'))); }
  }
}
var renderType_Pictures_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Pictures_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Pictures>;
  _Pictures_0_3:Wrapper_Pictures;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Pictures_Host0,renderType_Pictures_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Pictures0(this.viewUtils,this,0,this._el_0);
    this._Pictures_0_3 = new Wrapper_Pictures(this.injectorGet(import8.DomSanitizer,this.parentIndex),this.injectorGet(import9.DataService,this.parentIndex),this.injectorGet(import9.CacheManager,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex),this.injector(0));
    this.compView_0.create(this._Pictures_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Pictures_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Pictures) && (0 === requestNodeIndex))) { return this._Pictures_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Pictures_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Pictures_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._Pictures_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PicturesNgFactory:import7.ComponentFactory<import0.Pictures> = new import7.ComponentFactory<import0.Pictures>('ng-component',View_Pictures_Host0,import0.Pictures);
const styles_Pictures:any[] = [import11.styles];
var renderType_Pictures:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_Pictures,{});
export class View_Pictures0 extends import1.AppView<import0.Pictures> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import13.Wrapper_NgFor;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _vc_19:import12.ViewContainer;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import13.Wrapper_NgFor;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _pipe_translate_0:import14.TranslatePipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Pictures0,renderType_Pictures,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import13.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray16(10,'aria-labelledby','myModalLabel','class','modal fade','id','myModal','role','dialog','tabindex','-1'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray4(4,'class','modal-dialog','role','document'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','modal-content'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','modal-body'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray8(8,'class','carousel slide','data-interval','false','data-ride','carousel','id','carousel-example-generic'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n\n\n                    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray4(4,'class','carousel-inner','role','listbox'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._vc_19 = new import12.ViewContainer(19,17,this,this._anchor_19);
    this._TemplateRef_19_5 = new import15.TemplateRef_(this,19,this._anchor_19);
    this._NgFor_19_6 = new import13.Wrapper_NgFor(this._vc_19.vcRef,this._TemplateRef_19_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_20 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_14,'a',new import3.InlineArray8(8,'class','left carousel-control','data-slide','prev','href','#carousel-example-generic','role','button'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-chevron-left'),(null as any));
    this._text_26 = this.renderer.createText(this._el_23,'\n                        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Previous',(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_14,'a',new import3.InlineArray8(8,'class','right carousel-control','data-slide','next','href','#carousel-example-generic','role','button'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-chevron-right'),(null as any));
    this._text_34 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Next',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n                    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_39 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_40 = this.renderer.createText(this._el_10,'\n\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._text_43 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._pipe_translate_0 = new import14.TranslatePipe(this.parentView.injectorGet(import9.TranslationService,this.parentIndex),this.parentView.injectorGet(import9.CacheManager,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    if (((token === import15.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.images;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_19_0_0:any = this.context.images;
    this._NgFor_19_6.check_ngForOf(currVal_19_0_0,throwOnChange,false);
    this._NgFor_19_6.ngDoCheck(this,this._anchor_19,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_19.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_19.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_Pictures1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 19)) { return new View_Pictures2(this.viewUtils,this,19,this._anchor_19,this._vc_19); }
    return (null as any);
  }
}
class View_Pictures1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_Pictures1,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-lg-3 col-md-4 col-sm-6 col-xs-12 text-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray8(8,'alt','','class','img-responsive img-rounded','data-target','#myModal','data-toggle','modal'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = this.context.$implicit.ImageURL;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.selectedID = this.context.$implicit.ID)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Pictures2 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import20.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  _pipe_translate_0_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_Pictures2,renderType_Pictures,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import18.UNINITIALIZED;
    this._expr_9 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_0_3 = new import20.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import21.KeyValueDiffers,this.parentView.parentIndex),new import22.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray4(4,'alt','...','class','img-carousel img-responsive'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','carousel-caption'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._pipe_translate_0_0 = import3.pureProxy1((<View_Pictures0>this.parentView)._pipe_translate_0.transform.bind((<View_Pictures0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_0_0_0:any = this.parentView.context.setClasses(this.context.$implicit.ID);
    this._NgClass_0_3.check_ngClass(currVal_0_0_0,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_8:any = this.context.$implicit.ImageURL;
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    valUnwrapper.reset();
    const currVal_9:any = import3.inlineInterpolate(1,'\n                                ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,(<View_Pictures0>this.parentView)._pipe_translate_0.transform)('Noya Schleien')),'\n                            ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_5,currVal_9);
      this._expr_9 = currVal_9;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}