export const CARDS_LOADED="CARDS_LOADED";
export const LOAD_CARDS="LOAD_CARDS";
export const LOAD_HOME_PAGE_TEXT="LOAD_HOME_PAGE_TEXT";
export const HOME_PAGE_TEXT_LOADED="HOME_PAGE_TEXT_LOADED";
export const LOAD_CVs="LOAD_CVs";
export const CVs_LOADED="CVs_LOADED";



