/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Contact/contact';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/services';
import * as import9 from '@angular/router/src/router';
import * as import10 from './contact.css.shim.ngstyle';
import * as import11 from '@angular/core/src/animation/animation_transition';
import * as import12 from '@angular/core/src/animation/animation_sequence_player';
import * as import13 from '@angular/core/src/animation/animation_styles';
import * as import14 from '@angular/core/src/animation/animation_style_util';
import * as import15 from '@angular/core/src/animation/animation_keyframe';
import * as import16 from '@angular/core/src/animation/animation_player';
import * as import17 from '@angular/core/src/linker/view_container';
import * as import18 from '@angular/core/src/change_detection/change_detection_util';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import25 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '../common/invalid-email.directive.ngfactory';
import * as import27 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import28 from '../../../app/pipes/pipes';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import33 from '@angular/forms/src/directives/default_value_accessor';
import * as import34 from '@angular/forms/src/directives/validators';
import * as import35 from '@angular/forms/src/validators';
import * as import36 from '@angular/forms/src/directives/control_value_accessor';
import * as import37 from '@angular/forms/src/directives/ng_model';
import * as import38 from '@angular/forms/src/directives/ng_control';
import * as import39 from '@angular/forms/src/directives/ng_control_status';
import * as import40 from '@angular/common/src/directives/ng_if';
import * as import41 from '../../../app/common/invalid-email.directive';
import * as import42 from '@angular/common/src/directives/ng_class';
import * as import43 from '@angular/forms/src/directives/ng_form';
import * as import44 from '@angular/forms/src/directives/control_container';
export class Wrapper_Contact {
  /*private*/ _eventHandler:Function;
  context:import0.Contact;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.Contact(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Contact_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Contact_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Contact>;
  _Contact_0_3:Wrapper_Contact;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Contact_Host0,renderType_Contact_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Contact0(this.viewUtils,this,0,this._el_0);
    this._Contact_0_3 = new Wrapper_Contact(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import8.CacheManager,this.parentIndex),this.injectorGet(import8.DialogService,this.parentIndex),this.injectorGet(import8.DialogService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injector(0));
    this.compView_0.create(this._Contact_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Contact_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Contact) && (0 === requestNodeIndex))) { return this._Contact_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Contact_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._Contact_0_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._Contact_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ContactNgFactory:import7.ComponentFactory<import0.Contact> = new import7.ComponentFactory<import0.Contact>('ng-component',View_Contact_Host0,import0.Contact);
const styles_Contact:any[] = [import10.styles];
var Contact_invalidAnimation_states:any = {
  'in': {
    'transform': 'translateX(0)',
    'opacity': '1'
  }
  ,
  '*': {},
  'void': {}
}
;
function Contact_invalidAnimation_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import11.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'invalidAnimation'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = Contact_invalidAnimation_states['*'];
  var startStateStyles:any = Contact_invalidAnimation_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = Contact_invalidAnimation_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import12.AnimationSequencePlayer([view.renderer.animate(element,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'transform': 'translateX(-100%)',
          'opacity': '0'
        }

      ]
      )),import14.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import15.AnimationKeyframe(0,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{}]))),
        new import15.AnimationKeyframe(1,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,(null as any),previousPlayers)]);
    totalTime = 500;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import12.AnimationSequencePlayer([view.renderer.animate(element,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import15.AnimationKeyframe(0,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{
            'transform': 'true',
            'opacity': 'true'
          }
        ]))),
          new import15.AnimationKeyframe(1,new import13.AnimationStyles(import14.collectAndResolveStyles(collectedStyles,[{
            'transform': 'translateX(-100%)',
            'opacity': '0'
          }
        ])))
      ]
    ,500,0,(null as any),previousPlayers)]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import16.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import14.renderStyles(element,view.renderer,import14.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import12.AnimationSequencePlayer(previousPlayers).destroy();
  import14.renderStyles(element,view.renderer,import14.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'invalidAnimation',player);
  return new import11.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_Contact1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_translate_0_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Contact1,renderType_Contact,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import18.UNINITIALIZED;
    this._expr_3 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','invalid-label'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_translate_0_1 = import3.pureProxy1((<View_Contact0>this.parentView)._pipe_translate_0.transform.bind((<View_Contact0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_2:any = 'in';
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,((this._expr_2 == import18.UNINITIALIZED)? 'void': this._expr_2),((currVal_2 == import18.UNINITIALIZED)? 'void': currVal_2));
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'\n                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,(<View_Contact0>this.parentView)._pipe_translate_0.transform)(this.parentView.context.formErrors.name)),'\n                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  detachInternal():void {
    var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,this._expr_2,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Contact2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_translate_0_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Contact2,renderType_Contact,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import18.UNINITIALIZED;
    this._expr_3 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','invalid-label'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_translate_0_3 = import3.pureProxy1((<View_Contact0>this.parentView)._pipe_translate_0.transform.bind((<View_Contact0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_2:any = 'in';
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,((this._expr_2 == import18.UNINITIALIZED)? 'void': this._expr_2),((currVal_2 == import18.UNINITIALIZED)? 'void': currVal_2));
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'\n                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_3,(<View_Contact0>this.parentView)._pipe_translate_0.transform)(this.parentView.context.formErrors.email)),'\n                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  detachInternal():void {
    var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,this._expr_2,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Contact3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_translate_0_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Contact3,renderType_Contact,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import18.UNINITIALIZED;
    this._expr_3 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','invalid-label'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_translate_0_5 = import3.pureProxy1((<View_Contact0>this.parentView)._pipe_translate_0.transform.bind((<View_Contact0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_2:any = 'in';
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,((this._expr_2 == import18.UNINITIALIZED)? 'void': this._expr_2),((currVal_2 == import18.UNINITIALIZED)? 'void': currVal_2));
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'\n                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_5,(<View_Contact0>this.parentView)._pipe_translate_0.transform)(this.parentView.context.formErrors.content)),'\n                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  detachInternal():void {
    var animationTransition_invalidAnimation:any = this.componentType.animations['invalidAnimation'](this,this._el_0,this._expr_2,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_Contact:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_Contact,{'invalidAnimation': Contact_invalidAnimation_factory});
export class View_Contact0 extends import1.AppView<import0.Contact> {
  _viewQuery_contactForm_0:import19.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _NgForm_5_3:import20.Wrapper_NgForm;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import21.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_9_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_9_5:any[];
  _NG_VALUE_ACCESSOR_9_6:any[];
  _NgModel_9_7:import24.Wrapper_NgModel;
  _NgControl_9_8:any;
  _NgControlStatus_9_9:import21.Wrapper_NgControlStatus;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import17.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import25.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_16_4:import23.Wrapper_RequiredValidator;
  _EmailValidatorDirective_16_5:import26.Wrapper_EmailValidatorDirective;
  _NG_VALIDATORS_16_6:any[];
  _NG_VALUE_ACCESSOR_16_7:any[];
  _NgModel_16_8:import24.Wrapper_NgModel;
  _NgControl_16_9:any;
  _NgControlStatus_16_10:import21.Wrapper_NgControlStatus;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import17.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import25.Wrapper_NgIf;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import24.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import21.Wrapper_NgControlStatus;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import17.ViewContainer;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import25.Wrapper_NgIf;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _NgClass_30_3:import27.Wrapper_NgClass;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  /*private*/ _expr_118:any;
  /*private*/ _expr_119:any;
  /*private*/ _expr_120:any;
  /*private*/ _expr_121:any;
  _pipe_translate_0:import28.TranslatePipe;
  _pipe_translate_0_0:any;
  /*private*/ _expr_124:any;
  /*private*/ _expr_125:any;
  /*private*/ _expr_126:any;
  _pipe_translate_0_2:any;
  /*private*/ _expr_128:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  _pipe_translate_0_4:any;
  _map_132:any;
  /*private*/ _expr_133:any;
  /*private*/ _expr_134:any;
  _pipe_translate_0_6:any;
  /*private*/ _expr_136:any;
  /*private*/ _expr_137:any;
  /*private*/ _expr_138:any;
  /*private*/ _expr_139:any;
  /*private*/ _expr_140:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Contact0,renderType_Contact,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_118 = import18.UNINITIALIZED;
    this._expr_119 = import18.UNINITIALIZED;
    this._expr_120 = import18.UNINITIALIZED;
    this._expr_121 = import18.UNINITIALIZED;
    this._expr_124 = import18.UNINITIALIZED;
    this._expr_125 = import18.UNINITIALIZED;
    this._expr_126 = import18.UNINITIALIZED;
    this._expr_128 = import18.UNINITIALIZED;
    this._expr_129 = import18.UNINITIALIZED;
    this._expr_130 = import18.UNINITIALIZED;
    this._map_132 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'text-right': p0,
        'text-left': p1
      }
      ;
    });
    this._expr_133 = import18.UNINITIALIZED;
    this._expr_134 = import18.UNINITIALIZED;
    this._expr_136 = import18.UNINITIALIZED;
    this._expr_137 = import18.UNINITIALIZED;
    this._expr_138 = import18.UNINITIALIZED;
    this._expr_139 = import18.UNINITIALIZED;
    this._expr_140 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_contactForm_0 = new import19.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','white-panel contact-form'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'form',new import3.InlineArray2(2,'novalidate',''),(null as any));
    this._NgForm_5_3 = new import20.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_5_4 = this._NgForm_5_3.context;
    this._NgControlStatusGroup_5_5 = new import21.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group  '),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray8(8,'class','form-control form-field input-lg ','name','name','required','','type','text'),(null as any));
    this._DefaultValueAccessor_9_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import29.ElementRef(this._el_9));
    this._RequiredValidator_9_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_9_5 = [this._RequiredValidator_9_4.context];
    this._NG_VALUE_ACCESSOR_9_6 = [this._DefaultValueAccessor_9_3.context];
    this._NgModel_9_7 = new import24.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_9_5,(null as any),this._NG_VALUE_ACCESSOR_9_6);
    this._NgControl_9_8 = this._NgModel_9_7.context;
    this._NgControlStatus_9_9 = new import21.Wrapper_NgControlStatus(this._NgControl_9_8);
    this._text_10 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._vc_11 = new import17.ViewContainer(11,7,this,this._anchor_11);
    this._TemplateRef_11_5 = new import30.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import25.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'input',new import3.InlineArray16(10,'class','form-control form-field input-lg','emailValidator','','name','email','required','','type','email'),(null as any));
    this._DefaultValueAccessor_16_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import29.ElementRef(this._el_16));
    this._RequiredValidator_16_4 = new import23.Wrapper_RequiredValidator();
    this._EmailValidatorDirective_16_5 = new import26.Wrapper_EmailValidatorDirective();
    this._NG_VALIDATORS_16_6 = [
      this._RequiredValidator_16_4.context,
      this._EmailValidatorDirective_16_5.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_16_7 = [this._DefaultValueAccessor_16_3.context];
    this._NgModel_16_8 = new import24.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_16_6,(null as any),this._NG_VALUE_ACCESSOR_16_7);
    this._NgControl_16_9 = this._NgModel_16_8.context;
    this._NgControlStatus_16_10 = new import21.Wrapper_NgControlStatus(this._NgControl_16_9);
    this._text_17 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._vc_18 = new import17.ViewContainer(18,14,this,this._anchor_18);
    this._TemplateRef_18_5 = new import30.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import25.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'textarea',new import3.InlineArray8(8,'class','form-control input-lg','name','content','required','','rows','8'),(null as any));
    this._DefaultValueAccessor_23_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import29.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import24.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import21.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._vc_25 = new import17.ViewContainer(25,21,this,this._anchor_25);
    this._TemplateRef_25_5 = new import30.TemplateRef_(this,25,this._anchor_25);
    this._NgIf_25_6 = new import25.Wrapper_NgIf(this._vc_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_27 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-12'),(null as any));
    this._NgClass_30_3 = new import27.Wrapper_NgClass(this.parentView.injectorGet(import31.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import32.KeyValueDiffers,this.parentIndex),new import29.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_30,'\n                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'button',new import3.InlineArray4(4,'class','btn btn-info','type','submit'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n\n                ',(null as any));
    this._text_35 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_5,'span',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'message not sent - plz try again later',(null as any));
    this._text_39 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'You have submitted the following:',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n            ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Name:',(null as any));
    this._text_51 = this.renderer.createText(this._el_47,'\n            ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_47,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'',(null as any));
    this._text_54 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_55 = this.renderer.createText(this._el_42,'\n\n        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n            ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Email:',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,'\n            ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'',(null as any));
    this._text_63 = this.renderer.createText(this._el_56,'\n        ',(null as any));
    this._text_64 = this.renderer.createText(this._el_42,'\n\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n            ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'Content:',(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'\n            ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'',(null as any));
    this._text_72 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_42,'\n\n\n        ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'\n            ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_74,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'Send Another',(null as any));
    this._text_78 = this.renderer.createText(this._el_74,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_42,'\n\n    ',(null as any));
    this._text_80 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_81 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    this._NgForm_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_9));
    this._NgModel_9_7.subscribe(this,this.eventHandler(this.handleEvent_9),true);
    this._pipe_translate_0 = new import28.TranslatePipe(this.parentView.injectorGet(import8.TranslationService,this.parentIndex),this.parentView.injectorGet(import8.CacheManager,this.parentIndex));
    this._pipe_translate_0_0 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_16));
    this._NgModel_16_8.subscribe(this,this.eventHandler(this.handleEvent_16),true);
    this._pipe_translate_0_2 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_7.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    this._pipe_translate_0_4 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this._pipe_translate_0_6 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_76,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_76));
    this._viewQuery_contactForm_0.reset([this._NgForm_5_3.context]);
    this.context.currentForm = this._viewQuery_contactForm_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import34.RequiredValidator) && (9 === requestNodeIndex))) { return this._RequiredValidator_9_4.context; }
    if (((token === import35.NG_VALIDATORS) && (9 === requestNodeIndex))) { return this._NG_VALIDATORS_9_5; }
    if (((token === import36.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_6; }
    if (((token === import37.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_7.context; }
    if (((token === import38.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_8; }
    if (((token === import39.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_9.context; }
    if (((token === import30.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import40.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import33.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3.context; }
    if (((token === import34.RequiredValidator) && (16 === requestNodeIndex))) { return this._RequiredValidator_16_4.context; }
    if (((token === import41.EmailValidatorDirective) && (16 === requestNodeIndex))) { return this._EmailValidatorDirective_16_5.context; }
    if (((token === import35.NG_VALIDATORS) && (16 === requestNodeIndex))) { return this._NG_VALIDATORS_16_6; }
    if (((token === import36.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_7; }
    if (((token === import37.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_8.context; }
    if (((token === import38.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_9; }
    if (((token === import39.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_10.context; }
    if (((token === import30.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import40.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import33.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import34.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import35.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import36.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import37.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import38.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import39.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    if (((token === import30.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import40.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import42.NgClass) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgClass_30_3.context; }
    if (((token === import43.NgForm) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgForm_5_3.context; }
    if (((token === import44.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ControlContainer_5_4; }
    if (((token === import39.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    this._NgForm_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = '';
    this._RequiredValidator_9_4.check_required(currVal_9_1_0,throwOnChange,false);
    this._RequiredValidator_9_4.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_2_0:any = 'name';
    this._NgModel_9_7.check_name(currVal_9_2_0,throwOnChange,false);
    const currVal_9_2_1:any = this.context.isSubmitting;
    this._NgModel_9_7.check_isDisabled(currVal_9_2_1,throwOnChange,false);
    const currVal_9_2_2:any = this.context.message.Sender.Name;
    this._NgModel_9_7.check_model(currVal_9_2_2,throwOnChange,false);
    this._NgModel_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_9.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:any = this.context.formErrors.name;
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    this._DefaultValueAccessor_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_1_0:any = '';
    this._RequiredValidator_16_4.check_required(currVal_16_1_0,throwOnChange,false);
    this._RequiredValidator_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    this._EmailValidatorDirective_16_5.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_3_0:any = 'email';
    this._NgModel_16_8.check_name(currVal_16_3_0,throwOnChange,false);
    const currVal_16_3_1:any = this.context.isSubmitting;
    this._NgModel_16_8.check_isDisabled(currVal_16_3_1,throwOnChange,false);
    const currVal_16_3_2:any = this.context.message.Sender.Email;
    this._NgModel_16_8.check_model(currVal_16_3_2,throwOnChange,false);
    this._NgModel_16_8.ngDoCheck(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_10.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_18_0_0:any = this.context.formErrors.email;
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'content';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.context.isSubmitting;
    this._NgModel_23_7.check_isDisabled(currVal_23_2_1,throwOnChange,false);
    const currVal_23_2_2:any = this.context.message.Content;
    this._NgModel_23_7.check_model(currVal_23_2_2,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_25_0_0:any = this.context.formErrors.content;
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    const currVal_30_0_0:any = 'col-xs-12';
    this._NgClass_30_3.check_klass(currVal_30_0_0,throwOnChange,false);
    const currVal_30_0_1:any = this._map_132(this.context.isEng,this.context.isHeb);
    this._NgClass_30_3.check_ngClass(currVal_30_0_1,throwOnChange,false);
    this._NgClass_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    const currVal_118:any = this.context.submitted;
    if (import3.checkBinding(throwOnChange,this._expr_118,currVal_118)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_118);
      this._expr_118 = currVal_118;
    }
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    const currVal_119:boolean = (!this._NgModel_9_7.context.valid && !this._NgModel_9_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_119,currVal_119)) {
      this.renderer.setElementClass(this._el_7,'has-error',currVal_119);
      this._expr_119 = currVal_119;
    }
    const currVal_120:any = (this._NgModel_9_7.context.valid && !this._NgModel_9_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_120,currVal_120)) {
      this.renderer.setElementClass(this._el_7,'has-success',currVal_120);
      this._expr_120 = currVal_120;
    }
    valUnwrapper.reset();
    const currVal_121:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,this._pipe_translate_0.transform)('Name')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_121,currVal_121))) {
      this.renderer.setElementProperty(this._el_9,'placeholder',currVal_121);
      this._expr_121 = currVal_121;
    }
    this._RequiredValidator_9_4.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_9_9.checkHost(this,this,this._el_9,throwOnChange);
    const currVal_124:any = this.context.invalidEmailInput(this._NgModel_16_8.context);
    if (import3.checkBinding(throwOnChange,this._expr_124,currVal_124)) {
      this.renderer.setElementClass(this._el_14,'has-error',currVal_124);
      this._expr_124 = currVal_124;
    }
    const currVal_125:boolean = (!this._NgModel_16_8.context.pristine && !this.context.invalidEmailInput(this._NgModel_16_8.context));
    if (import3.checkBinding(throwOnChange,this._expr_125,currVal_125)) {
      this.renderer.setElementClass(this._el_14,'has-success',currVal_125);
      this._expr_125 = currVal_125;
    }
    valUnwrapper.reset();
    const currVal_126:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_2,this._pipe_translate_0.transform)('Email')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_126,currVal_126))) {
      this.renderer.setElementProperty(this._el_16,'placeholder',currVal_126);
      this._expr_126 = currVal_126;
    }
    this._RequiredValidator_16_4.checkHost(this,this,this._el_16,throwOnChange);
    this._NgControlStatus_16_10.checkHost(this,this,this._el_16,throwOnChange);
    const currVal_128:boolean = (!this._NgModel_23_7.context.valid && !this._NgModel_23_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_128,currVal_128)) {
      this.renderer.setElementClass(this._el_21,'has-error',currVal_128);
      this._expr_128 = currVal_128;
    }
    const currVal_129:any = (this._NgModel_23_7.context.valid && !this._NgModel_23_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_129,currVal_129)) {
      this.renderer.setElementClass(this._el_21,'has-success',currVal_129);
      this._expr_129 = currVal_129;
    }
    valUnwrapper.reset();
    const currVal_130:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_4,this._pipe_translate_0.transform)('Content')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_130,currVal_130))) {
      this.renderer.setElementProperty(this._el_23,'placeholder',currVal_130);
      this._expr_130 = currVal_130;
    }
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    const currVal_133:any = (this.context.isSubmitting || !this._NgForm_5_3.context.form.valid);
    if (import3.checkBinding(throwOnChange,this._expr_133,currVal_133)) {
      this.renderer.setElementProperty(this._el_32,'disabled',currVal_133);
      this._expr_133 = currVal_133;
    }
    valUnwrapper.reset();
    const currVal_134:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_6,this._pipe_translate_0.transform)('Submit')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_134,currVal_134))) {
      this.renderer.setText(this._text_33,currVal_134);
      this._expr_134 = currVal_134;
    }
    const currVal_136:boolean = (!this.context.displaySubmitError || this.context.isSubmitting);
    if (import3.checkBinding(throwOnChange,this._expr_136,currVal_136)) {
      this.renderer.setElementProperty(this._el_37,'hidden',currVal_136);
      this._expr_136 = currVal_136;
    }
    const currVal_137:boolean = !this.context.submitted;
    if (import3.checkBinding(throwOnChange,this._expr_137,currVal_137)) {
      this.renderer.setElementProperty(this._el_42,'hidden',currVal_137);
      this._expr_137 = currVal_137;
    }
    const currVal_138:any = import3.inlineInterpolate(1,'',this.context.message.Sender.Name,'');
    if (import3.checkBinding(throwOnChange,this._expr_138,currVal_138)) {
      this.renderer.setText(this._text_53,currVal_138);
      this._expr_138 = currVal_138;
    }
    const currVal_139:any = import3.inlineInterpolate(1,'',this.context.message.Sender.Email,'');
    if (import3.checkBinding(throwOnChange,this._expr_139,currVal_139)) {
      this.renderer.setText(this._text_62,currVal_139);
      this._expr_139 = currVal_139;
    }
    const currVal_140:any = import3.inlineInterpolate(1,'',this.context.message.Content,'');
    if (import3.checkBinding(throwOnChange,this._expr_140,currVal_140)) {
      this.renderer.setText(this._text_71,currVal_140);
      this._expr_140 = currVal_140;
    }
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._NgModel_9_7.ngOnDestroy();
    this._NgModel_16_8.ngOnDestroy();
    this._NgModel_23_7.ngOnDestroy();
    this._NgForm_5_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 11)) { return new View_Contact1(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    if ((nodeIndex == 18)) { return new View_Contact2(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 25)) { return new View_Contact3(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Sender.Name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_16_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Sender.Email = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Content = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_76(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.submitted = false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}