/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Contact/contact';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/services';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import15 from '../../../app/pipes/pipes';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/validators';
import * as import20 from '@angular/forms/src/validators';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from '@angular/forms/src/directives/ng_form';
import * as import26 from '@angular/forms/src/directives/control_container';
export class Wrapper_Contact {
  /*private*/ _eventHandler:Function;
  context:import0.Contact;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.Contact(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Contact_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Contact_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Contact>;
  _Contact_0_3:Wrapper_Contact;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Contact_Host0,renderType_Contact_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Contact0(this.viewUtils,this,0,this._el_0);
    this._Contact_0_3 = new Wrapper_Contact(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import8.DialogService,this.parentIndex),this.injectorGet(import8.DialogService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injector(0));
    this.compView_0.create(this._Contact_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Contact_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Contact) && (0 === requestNodeIndex))) { return this._Contact_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Contact_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._Contact_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ContactNgFactory:import7.ComponentFactory<import0.Contact> = new import7.ComponentFactory<import0.Contact>('ng-component',View_Contact_Host0,import0.Contact);
const styles_Contact:any[] = ([] as any[]);
var renderType_Contact:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_Contact,{});
export class View_Contact0 extends import1.AppView<import0.Contact> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _NgForm_5_3:import10.Wrapper_NgForm;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import11.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_10_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_10_5:any[];
  _NG_VALUE_ACCESSOR_10_6:any[];
  _NgModel_10_7:import14.Wrapper_NgModel;
  _NgControl_10_8:any;
  _NgControlStatus_10_9:import11.Wrapper_NgControlStatus;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_17_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_17_5:any[];
  _NG_VALUE_ACCESSOR_17_6:any[];
  _NgModel_17_7:import14.Wrapper_NgModel;
  _NgControl_17_8:any;
  _NgControlStatus_17_9:import11.Wrapper_NgControlStatus;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import14.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import11.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  /*private*/ _expr_98:any;
  /*private*/ _expr_99:any;
  _pipe_translate_0:import15.TranslatePipe;
  _pipe_translate_0_0:any;
  /*private*/ _expr_102:any;
  _pipe_translate_0_1:any;
  /*private*/ _expr_104:any;
  _pipe_translate_0_2:any;
  /*private*/ _expr_106:any;
  /*private*/ _expr_107:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  /*private*/ _expr_110:any;
  /*private*/ _expr_111:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Contact0,renderType_Contact,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_98 = import16.UNINITIALIZED;
    this._expr_99 = import16.UNINITIALIZED;
    this._expr_102 = import16.UNINITIALIZED;
    this._expr_104 = import16.UNINITIALIZED;
    this._expr_106 = import16.UNINITIALIZED;
    this._expr_107 = import16.UNINITIALIZED;
    this._expr_108 = import16.UNINITIALIZED;
    this._expr_109 = import16.UNINITIALIZED;
    this._expr_110 = import16.UNINITIALIZED;
    this._expr_111 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','white-panel contact-form'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_5_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_5_4 = this._NgForm_5_3.context;
    this._NgControlStatusGroup_5_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray16(10,'class','form-control form-field input-lg','name','Name','ngControl','name','required','','type','text'),(null as any));
    this._DefaultValueAccessor_10_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_10_5 = [this._RequiredValidator_10_4.context];
    this._NG_VALUE_ACCESSOR_10_6 = [this._DefaultValueAccessor_10_3.context];
    this._NgModel_10_7 = new import14.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_10_5,(null as any),this._NG_VALUE_ACCESSOR_10_6);
    this._NgControl_10_8 = this._NgModel_10_7.context;
    this._NgControlStatus_10_9 = new import11.Wrapper_NgControlStatus(this._NgControl_10_8);
    this._text_11 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_16 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_14,'input',new import3.InlineArray16(10,'class','form-control form-field input-lg','name','Email','ngControl','email','required','','type','email'),(null as any));
    this._DefaultValueAccessor_17_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_17));
    this._RequiredValidator_17_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_17_5 = [this._RequiredValidator_17_4.context];
    this._NG_VALUE_ACCESSOR_17_6 = [this._DefaultValueAccessor_17_3.context];
    this._NgModel_17_7 = new import14.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_17_5,(null as any),this._NG_VALUE_ACCESSOR_17_6);
    this._NgControl_17_8 = this._NgModel_17_7.context;
    this._NgControlStatus_17_9 = new import11.Wrapper_NgControlStatus(this._NgControl_17_8);
    this._text_18 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_20,'textarea',new import3.InlineArray16(10,'class','form-control input-lg','name','Content','ngControl','content','required','','rows','8'),(null as any));
    this._DefaultValueAccessor_23_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import14.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import11.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray4(4,'class','btn btn-default','type','submit'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Submit',(null as any));
    this._text_28 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_5,'span',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'message not sent - plz try again later',(null as any));
    this._text_31 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'You have submitted the following:',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Name:',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText(this._el_39,'\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_34,'\n\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n            ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'Email:',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n            ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'',(null as any));
    this._text_55 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_34,'\n\n        ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','row back-cornsilk-color margin-row black-border x-large-font'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-1'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Content:',(null as any));
    this._text_61 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_57,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-11'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'',(null as any));
    this._text_64 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_34,'\n\n\n        ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n            ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Send Another',(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'\n        ',(null as any));
    this._text_71 = this.renderer.createText(this._el_34,'\n\n    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_73 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    this._NgForm_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_7.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    this._pipe_translate_0 = new import15.TranslatePipe(this.parentView.injectorGet(import8.TranslationService,this.parentIndex),this.parentView.injectorGet(import8.CacheManager,this.parentIndex));
    this._pipe_translate_0_0 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    this._NgModel_17_7.subscribe(this,this.eventHandler(this.handleEvent_17),true);
    this._pipe_translate_0_1 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_7.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    this._pipe_translate_0_2 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_68,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_68));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3.context; }
    if (((token === import19.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4.context; }
    if (((token === import20.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_6; }
    if (((token === import22.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_7.context; }
    if (((token === import23.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_8; }
    if (((token === import24.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_9.context; }
    if (((token === import18.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import19.RequiredValidator) && (17 === requestNodeIndex))) { return this._RequiredValidator_17_4.context; }
    if (((token === import20.NG_VALIDATORS) && (17 === requestNodeIndex))) { return this._NG_VALIDATORS_17_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_6; }
    if (((token === import22.NgModel) && (17 === requestNodeIndex))) { return this._NgModel_17_7.context; }
    if (((token === import23.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_8; }
    if (((token === import24.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_9.context; }
    if (((token === import18.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import19.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import20.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import22.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import23.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import24.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    if (((token === import25.NgForm) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgForm_5_3.context; }
    if (((token === import26.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ControlContainer_5_4; }
    if (((token === import24.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import16.ValueUnwrapper();
    this._NgForm_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = '';
    this._RequiredValidator_10_4.check_required(currVal_10_1_0,throwOnChange,false);
    this._RequiredValidator_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_2_0:any = 'Name';
    this._NgModel_10_7.check_name(currVal_10_2_0,throwOnChange,false);
    const currVal_10_2_1:any = this.context.isSubmitting;
    this._NgModel_10_7.check_isDisabled(currVal_10_2_1,throwOnChange,false);
    const currVal_10_2_2:any = this.context.message.Sender.Name;
    this._NgModel_10_7.check_model(currVal_10_2_2,throwOnChange,false);
    this._NgModel_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.ngDoCheck(this,this._el_10,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = '';
    this._RequiredValidator_17_4.check_required(currVal_17_1_0,throwOnChange,false);
    this._RequiredValidator_17_4.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_2_0:any = 'Email';
    this._NgModel_17_7.check_name(currVal_17_2_0,throwOnChange,false);
    const currVal_17_2_1:any = this.context.isSubmitting;
    this._NgModel_17_7.check_isDisabled(currVal_17_2_1,throwOnChange,false);
    const currVal_17_2_2:any = this.context.message.Sender.Email;
    this._NgModel_17_7.check_model(currVal_17_2_2,throwOnChange,false);
    this._NgModel_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_9.ngDoCheck(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'Content';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.context.isSubmitting;
    this._NgModel_23_7.check_isDisabled(currVal_23_2_1,throwOnChange,false);
    const currVal_23_2_2:any = this.context.message.Content;
    this._NgModel_23_7.check_model(currVal_23_2_2,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_98:any = this.context.submitted;
    if (import3.checkBinding(throwOnChange,this._expr_98,currVal_98)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_98);
      this._expr_98 = currVal_98;
    }
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    valUnwrapper.reset();
    const currVal_99:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,this._pipe_translate_0.transform)('Name')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_99,currVal_99))) {
      this.renderer.setElementProperty(this._el_10,'placeholder',currVal_99);
      this._expr_99 = currVal_99;
    }
    this._RequiredValidator_10_4.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.checkHost(this,this,this._el_10,throwOnChange);
    valUnwrapper.reset();
    const currVal_102:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,this._pipe_translate_0.transform)('Email')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_102,currVal_102))) {
      this.renderer.setElementProperty(this._el_17,'placeholder',currVal_102);
      this._expr_102 = currVal_102;
    }
    this._RequiredValidator_17_4.checkHost(this,this,this._el_17,throwOnChange);
    this._NgControlStatus_17_9.checkHost(this,this,this._el_17,throwOnChange);
    valUnwrapper.reset();
    const currVal_104:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_2,this._pipe_translate_0.transform)('Content')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_104,currVal_104))) {
      this.renderer.setElementProperty(this._el_23,'placeholder',currVal_104);
      this._expr_104 = currVal_104;
    }
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    const currVal_106:any = this.context.isSubmitting;
    if (import3.checkBinding(throwOnChange,this._expr_106,currVal_106)) {
      this.renderer.setElementProperty(this._el_26,'disabled',currVal_106);
      this._expr_106 = currVal_106;
    }
    const currVal_107:boolean = (!this.context.displaySubmitError || this.context.isSubmitting);
    if (import3.checkBinding(throwOnChange,this._expr_107,currVal_107)) {
      this.renderer.setElementProperty(this._el_29,'hidden',currVal_107);
      this._expr_107 = currVal_107;
    }
    const currVal_108:boolean = !this.context.submitted;
    if (import3.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      this.renderer.setElementProperty(this._el_34,'hidden',currVal_108);
      this._expr_108 = currVal_108;
    }
    const currVal_109:any = import3.inlineInterpolate(1,'',this.context.message.Sender.Name,'');
    if (import3.checkBinding(throwOnChange,this._expr_109,currVal_109)) {
      this.renderer.setText(this._text_45,currVal_109);
      this._expr_109 = currVal_109;
    }
    const currVal_110:any = import3.inlineInterpolate(1,'',this.context.message.Sender.Email,'');
    if (import3.checkBinding(throwOnChange,this._expr_110,currVal_110)) {
      this.renderer.setText(this._text_54,currVal_110);
      this._expr_110 = currVal_110;
    }
    const currVal_111:any = import3.inlineInterpolate(1,'',this.context.message.Content,'');
    if (import3.checkBinding(throwOnChange,this._expr_111,currVal_111)) {
      this.renderer.setText(this._text_63,currVal_111);
      this._expr_111 = currVal_111;
    }
  }
  destroyInternal():void {
    this._NgModel_10_7.ngOnDestroy();
    this._NgModel_17_7.ngOnDestroy();
    this._NgModel_23_7.ngOnDestroy();
    this._NgForm_5_3.ngOnDestroy();
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Sender.Name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Sender.Email = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Content = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_68(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.submitted = false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}