/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.my-navbar[_ngcontent-%COMP%] {\n  background-color: rgba(21, 88, 135, 0.360784);\n  border: 0;\n  height: 100%; }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n     }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:hover {\n    background-color: transparent !important;\n     }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:before {\n    content: \'\';\n    display: block;\n    position: absolute;\n    left: 0;\n    bottom: 0;\n    height: 3px;\n    width: 0;\n    transition: width 0s ease, background .5s ease; }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:after {\n    content: \'\';\n    display: block;\n    position: absolute;\n    right: 0;\n    bottom: 0;\n    height: 3px;\n    width: 0;\n    background: white;\n    transition: width .5s ease; }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:hover:before {\n    width: 100%;\n    background: white;\n    transition: width .5s ease; }\n  .my-navbar[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:hover:after {\n    width: 100%;\n    background: transparent;\n    transition: all 0s ease; }'];