/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.col-xs-12[_ngcontent-%COMP%], .col-md-6[_ngcontent-%COMP%] {\n  transition: all 1s; }'];