/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.col-xs-12[_ngcontent-%COMP%], .col-md-6[_ngcontent-%COMP%] {\n  transition: all 1s; }'];
//# sourceMappingURL=videos.css.shim.ngstyle.js.map