/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.home-page-text[_ngcontent-%COMP%] {\n  font-size: larger;\n  padding: 15px;\n  \n  background: #f0f9ff;\n  \n  background: radial-gradient(ellipse at center, #f0f9ff 0%, #cbebff 47%, #a1dbff 100%);\n  \n  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr=\'#f0f9ff\', endColorstr=\'#a1dbff\',GradientType=1 );\n  \n  border-radius: 3em 1em;\n  font-family: \'GYADBR\'; }'];
//# sourceMappingURL=home.css.shim.ngstyle.js.map