/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Home/home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../app/services/services';
import * as import10 from './home.css.shim.ngstyle';
import * as import11 from '../../../app/Home/cards-manager';
import * as import12 from './cards-manager.ngfactory';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/security';
export class Wrapper_Home {
  /*private*/ _eventHandler:Function;
  context:import0.Home;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.Home(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Home_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Home_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Home>;
  _Home_0_3:Wrapper_Home;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Home_Host0,renderType_Home_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Home0(this.viewUtils,this,0,this._el_0);
    this._Home_0_3 = new Wrapper_Home(this.injectorGet(import8.Router,this.parentIndex),this.injector(0),this.injectorGet(import9.DataService,this.parentIndex),this.injectorGet(import9.CacheManager,this.parentIndex));
    this.compView_0.create(this._Home_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Home_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Home) && (0 === requestNodeIndex))) { return this._Home_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Home_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Home_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HomeNgFactory:import7.ComponentFactory<import0.Home> = new import7.ComponentFactory<import0.Home>('ng-component',View_Home_Host0,import0.Home);
const styles_Home:any[] = [import10.styles];
var renderType_Home:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_Home,{});
export class View_Home0 extends import1.AppView<import0.Home> {
  _text_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import11.CardsManagerComponent>;
  _CardsManagerComponent_5_3:import12.Wrapper_CardsManagerComponent;
  _text_6:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Home0,renderType_Home,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_9 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','home-page-text'),(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'cards-manager',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import12.View_CardsManagerComponent0(this.viewUtils,this,5,this._el_5);
    this._CardsManagerComponent_5_3 = new import12.Wrapper_CardsManagerComponent(this.parentView.injectorGet(import9.DataService,this.parentIndex),this.parentView.injectorGet(import9.CacheManager,this.parentIndex),this.injector(5));
    this.compView_5.create(this._CardsManagerComponent_5_3.context);
    this._text_6 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n\n\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.CardsManagerComponent) && (5 === requestNodeIndex))) { return this._CardsManagerComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CardsManagerComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_9:any = ((this.context.homePageText == null)? (null as any): this.context.homePageText.Text);
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_3,'innerHTML',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.HTML,currVal_9));
      this._expr_9 = currVal_9;
    }
    this.compView_5.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_5.destroy();
  }
}