/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/Home/traverse-item.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../app/services/services';
import * as import10 from './traverse-item.component.css.shim.ngstyle';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import16 from '../../../app/pipes/pipes';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/validators';
import * as import20 from '@angular/forms/src/validators';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from '@angular/forms/src/directives/ng_form';
import * as import26 from '@angular/forms/src/directives/control_container';
export class Wrapper_TraverseItemComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TraverseItemComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.TraverseItemComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_traverseItem(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.traverseItem = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TraverseItemComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TraverseItemComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TraverseItemComponent>;
  _TraverseItemComponent_0_3:Wrapper_TraverseItemComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TraverseItemComponent_Host0,renderType_TraverseItemComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'traverse-item',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TraverseItemComponent0(this.viewUtils,this,0,this._el_0);
    this._TraverseItemComponent_0_3 = new Wrapper_TraverseItemComponent(this.injectorGet(import9.DataService,this.parentIndex));
    this.compView_0.create(this._TraverseItemComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TraverseItemComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TraverseItemComponent) && (0 === requestNodeIndex))) { return this._TraverseItemComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TraverseItemComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TraverseItemComponentNgFactory:import8.ComponentFactory<import0.TraverseItemComponent> = new import8.ComponentFactory<import0.TraverseItemComponent>('traverse-item',View_TraverseItemComponent_Host0,import0.TraverseItemComponent);
const styles_TraverseItemComponent:any[] = [import10.styles];
var renderType_TraverseItemComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_TraverseItemComponent,{});
export class View_TraverseItemComponent0 extends import2.AppView<import0.TraverseItemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _NgForm_40_3:import11.Wrapper_NgForm;
  _ControlContainer_40_4:any;
  _NgControlStatusGroup_40_5:import12.Wrapper_NgControlStatusGroup;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _DefaultValueAccessor_49_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_49_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_49_5:any[];
  _NG_VALUE_ACCESSOR_49_6:any[];
  _NgModel_49_7:import15.Wrapper_NgModel;
  _NgControl_49_8:any;
  _NgControlStatus_49_9:import12.Wrapper_NgControlStatus;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _DefaultValueAccessor_63_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_63_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_63_5:any[];
  _NG_VALUE_ACCESSOR_63_6:any[];
  _NgModel_63_7:import15.Wrapper_NgModel;
  _NgControl_63_8:any;
  _NgControlStatus_63_9:import12.Wrapper_NgControlStatus;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _DefaultValueAccessor_77_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_77_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_77_5:any[];
  _NG_VALUE_ACCESSOR_77_6:any[];
  _NgModel_77_7:import15.Wrapper_NgModel;
  _NgControl_77_8:any;
  _NgControlStatus_77_9:import12.Wrapper_NgControlStatus;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  /*private*/ _expr_116:any;
  /*private*/ _expr_117:any;
  /*private*/ _expr_118:any;
  /*private*/ _expr_119:any;
  /*private*/ _expr_120:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  /*private*/ _expr_124:any;
  /*private*/ _expr_125:any;
  /*private*/ _expr_126:any;
  _pipe_translate_0:import16.TranslatePipe;
  _pipe_translate_0_0:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  _pipe_translate_0_1:any;
  /*private*/ _expr_132:any;
  _pipe_translate_0_2:any;
  /*private*/ _expr_134:any;
  /*private*/ _expr_135:any;
  _pipe_translate_0_3:any;
  /*private*/ _expr_137:any;
  _pipe_translate_0_4:any;
  /*private*/ _expr_139:any;
  /*private*/ _expr_140:any;
  _pipe_translate_0_5:any;
  /*private*/ _expr_142:any;
  /*private*/ _expr_143:any;
  /*private*/ _expr_144:any;
  /*private*/ _expr_145:any;
  _pipe_translate_0_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TraverseItemComponent0,renderType_TraverseItemComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_116 = import1.UNINITIALIZED;
    this._expr_117 = import1.UNINITIALIZED;
    this._expr_118 = import1.UNINITIALIZED;
    this._expr_119 = import1.UNINITIALIZED;
    this._expr_120 = import1.UNINITIALIZED;
    this._expr_121 = import1.UNINITIALIZED;
    this._expr_122 = import1.UNINITIALIZED;
    this._expr_123 = import1.UNINITIALIZED;
    this._expr_124 = import1.UNINITIALIZED;
    this._expr_125 = import1.UNINITIALIZED;
    this._expr_126 = import1.UNINITIALIZED;
    this._expr_129 = import1.UNINITIALIZED;
    this._expr_130 = import1.UNINITIALIZED;
    this._expr_132 = import1.UNINITIALIZED;
    this._expr_134 = import1.UNINITIALIZED;
    this._expr_135 = import1.UNINITIALIZED;
    this._expr_137 = import1.UNINITIALIZED;
    this._expr_139 = import1.UNINITIALIZED;
    this._expr_140 = import1.UNINITIALIZED;
    this._expr_142 = import1.UNINITIALIZED;
    this._expr_143 = import1.UNINITIALIZED;
    this._expr_144 = import1.UNINITIALIZED;
    this._expr_145 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','jumbotron','data-toggle','modal'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','h2 text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray8(8,'aria-labelledby','myModalLabel','class','modal fade','role','dialog','tabindex','-1'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray4(4,'class','modal-dialog','role','document'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','modal-content'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','modal-header'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray8(8,'aria-label','Close','class','close','data-dismiss','modal','type','button'),(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'×',(null as any));
    this._text_17 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_12,'h4',new import3.InlineArray4(4,'class','modal-title text-center','id','myModalLabel'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','modal-body'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','modal-footer text-center'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray4(4,'aria-expanded','false','data-toggle','collapse'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_30 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_32 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_25,'\n\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','collapse'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'div',new import3.InlineArray2(2,'class','well'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'form',new import3.InlineArray2(2,'class','text-center form-horizontal'),(null as any));
    this._NgForm_40_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_40_4 = this._NgForm_40_3.context;
    this._NgControlStatusGroup_40_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_40_4);
    this._text_41 = this.renderer.createText(this._el_40,'\n\n                        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'label',new import3.InlineArray4(4,'class','col-xs-2 control-label','for','name'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','col-xs-10'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                                ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'input',new import3.InlineArray16(10,'class','form-control','id','name','name','name','required','','type','text'),(null as any));
    this._DefaultValueAccessor_49_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_49));
    this._RequiredValidator_49_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_49_5 = [this._RequiredValidator_49_4.context];
    this._NG_VALUE_ACCESSOR_49_6 = [this._DefaultValueAccessor_49_3.context];
    this._NgModel_49_7 = new import15.Wrapper_NgModel(this._ControlContainer_40_4,this._NG_VALIDATORS_49_5,(null as any),this._NG_VALUE_ACCESSOR_49_6);
    this._NgControl_49_8 = this._NgModel_49_7.context;
    this._NgControlStatus_49_9 = new import12.Wrapper_NgControlStatus(this._NgControl_49_8);
    this._text_50 = this.renderer.createText(this._el_47,'\n                                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_47,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'',(null as any));
    this._text_53 = this.renderer.createText(this._el_47,'\n                            ',(null as any));
    this._text_54 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._text_55 = this.renderer.createText(this._el_40,'\n\n\n                        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n                            ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'label',new import3.InlineArray4(4,'class','col-xs-2 control-label','for','email'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,'\n                            ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray2(2,'class','col-xs-10'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n                                ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'input',new import3.InlineArray16(10,'class','form-control','id','email','name','email','required','','type','email'),(null as any));
    this._DefaultValueAccessor_63_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_63));
    this._RequiredValidator_63_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_63_5 = [this._RequiredValidator_63_4.context];
    this._NG_VALUE_ACCESSOR_63_6 = [this._DefaultValueAccessor_63_3.context];
    this._NgModel_63_7 = new import15.Wrapper_NgModel(this._ControlContainer_40_4,this._NG_VALIDATORS_63_5,(null as any),this._NG_VALUE_ACCESSOR_63_6);
    this._NgControl_63_8 = this._NgModel_63_7.context;
    this._NgControlStatus_63_9 = new import12.Wrapper_NgControlStatus(this._NgControl_63_8);
    this._text_64 = this.renderer.createText(this._el_61,'\n                                ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'',(null as any));
    this._text_67 = this.renderer.createText(this._el_61,'\n                            ',(null as any));
    this._text_68 = this.renderer.createText(this._el_56,'\n                        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_40,'\n\n                        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n                            ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_70,'label',new import3.InlineArray4(4,'class','col-xs-2 control-label','for','content'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'',(null as any));
    this._text_74 = this.renderer.createText(this._el_70,'\n                            ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_70,'div',new import3.InlineArray2(2,'class','col-xs-10'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n                                ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'textarea',new import3.InlineArray16(10,'class','form-control','id','content','name','content','required','','rows','3'),(null as any));
    this._DefaultValueAccessor_77_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_77));
    this._RequiredValidator_77_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_77_5 = [this._RequiredValidator_77_4.context];
    this._NG_VALUE_ACCESSOR_77_6 = [this._DefaultValueAccessor_77_3.context];
    this._NgModel_77_7 = new import15.Wrapper_NgModel(this._ControlContainer_40_4,this._NG_VALIDATORS_77_5,(null as any),this._NG_VALUE_ACCESSOR_77_6);
    this._NgControl_77_8 = this._NgModel_77_7.context;
    this._NgControlStatus_77_9 = new import12.Wrapper_NgControlStatus(this._NgControl_77_8);
    this._text_78 = this.renderer.createText(this._el_75,'\n                                ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_75,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'',(null as any));
    this._text_81 = this.renderer.createText(this._el_75,'\n                            ',(null as any));
    this._text_82 = this.renderer.createText(this._el_70,'\n                        ',(null as any));
    this._text_83 = this.renderer.createText(this._el_40,'\n\n                        ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray4(4,'class','submit','type','submit'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'',(null as any));
    this._text_86 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._text_87 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_88 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_89 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_90 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_91 = this.renderer.createText(this._el_6,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_27));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_40,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_40));
    this._NgForm_40_3.subscribe(this,this.eventHandler(this.handleEvent_40),true);
    this._pipe_translate_0 = new import16.TranslatePipe(this.parentView.injectorGet(import9.TranslationService,this.parentIndex),this.parentView.injectorGet(import9.CacheManager,this.parentIndex));
    this._pipe_translate_0_0 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_49));
    this._NgModel_49_7.subscribe(this,this.eventHandler(this.handleEvent_49),true);
    this._pipe_translate_0_1 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this._pipe_translate_0_2 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_63,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_63));
    this._NgModel_63_7.subscribe(this,this.eventHandler(this.handleEvent_63),true);
    this._pipe_translate_0_3 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this._pipe_translate_0_4 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_77,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_77));
    this._NgModel_77_7.subscribe(this,this.eventHandler(this.handleEvent_77),true);
    this._pipe_translate_0_5 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this._pipe_translate_0_6 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (49 === requestNodeIndex))) { return this._DefaultValueAccessor_49_3.context; }
    if (((token === import19.RequiredValidator) && (49 === requestNodeIndex))) { return this._RequiredValidator_49_4.context; }
    if (((token === import20.NG_VALIDATORS) && (49 === requestNodeIndex))) { return this._NG_VALIDATORS_49_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (49 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_49_6; }
    if (((token === import22.NgModel) && (49 === requestNodeIndex))) { return this._NgModel_49_7.context; }
    if (((token === import23.NgControl) && (49 === requestNodeIndex))) { return this._NgControl_49_8; }
    if (((token === import24.NgControlStatus) && (49 === requestNodeIndex))) { return this._NgControlStatus_49_9.context; }
    if (((token === import18.DefaultValueAccessor) && (63 === requestNodeIndex))) { return this._DefaultValueAccessor_63_3.context; }
    if (((token === import19.RequiredValidator) && (63 === requestNodeIndex))) { return this._RequiredValidator_63_4.context; }
    if (((token === import20.NG_VALIDATORS) && (63 === requestNodeIndex))) { return this._NG_VALIDATORS_63_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (63 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_63_6; }
    if (((token === import22.NgModel) && (63 === requestNodeIndex))) { return this._NgModel_63_7.context; }
    if (((token === import23.NgControl) && (63 === requestNodeIndex))) { return this._NgControl_63_8; }
    if (((token === import24.NgControlStatus) && (63 === requestNodeIndex))) { return this._NgControlStatus_63_9.context; }
    if (((token === import18.DefaultValueAccessor) && (77 === requestNodeIndex))) { return this._DefaultValueAccessor_77_3.context; }
    if (((token === import19.RequiredValidator) && (77 === requestNodeIndex))) { return this._RequiredValidator_77_4.context; }
    if (((token === import20.NG_VALIDATORS) && (77 === requestNodeIndex))) { return this._NG_VALIDATORS_77_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (77 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_77_6; }
    if (((token === import22.NgModel) && (77 === requestNodeIndex))) { return this._NgModel_77_7.context; }
    if (((token === import23.NgControl) && (77 === requestNodeIndex))) { return this._NgControl_77_8; }
    if (((token === import24.NgControlStatus) && (77 === requestNodeIndex))) { return this._NgControlStatus_77_9.context; }
    if (((token === import25.NgForm) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._NgForm_40_3.context; }
    if (((token === import26.ControlContainer) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._ControlContainer_40_4; }
    if (((token === import24.NgControlStatusGroup) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._NgControlStatusGroup_40_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this._NgForm_40_3.ngDoCheck(this,this._el_40,throwOnChange);
    this._NgControlStatusGroup_40_5.ngDoCheck(this,this._el_40,throwOnChange);
    this._DefaultValueAccessor_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_1_0:any = '';
    this._RequiredValidator_49_4.check_required(currVal_49_1_0,throwOnChange,false);
    this._RequiredValidator_49_4.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_2_0:any = 'name';
    this._NgModel_49_7.check_name(currVal_49_2_0,throwOnChange,false);
    const currVal_49_2_1:any = this.context.person.Name;
    this._NgModel_49_7.check_model(currVal_49_2_1,throwOnChange,false);
    this._NgModel_49_7.ngDoCheck(this,this._el_49,throwOnChange);
    this._NgControlStatus_49_9.ngDoCheck(this,this._el_49,throwOnChange);
    this._DefaultValueAccessor_63_3.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_63_1_0:any = '';
    this._RequiredValidator_63_4.check_required(currVal_63_1_0,throwOnChange,false);
    this._RequiredValidator_63_4.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_63_2_0:any = 'email';
    this._NgModel_63_7.check_name(currVal_63_2_0,throwOnChange,false);
    const currVal_63_2_1:any = this.context.person.Email;
    this._NgModel_63_7.check_model(currVal_63_2_1,throwOnChange,false);
    this._NgModel_63_7.ngDoCheck(this,this._el_63,throwOnChange);
    this._NgControlStatus_63_9.ngDoCheck(this,this._el_63,throwOnChange);
    this._DefaultValueAccessor_77_3.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_77_1_0:any = '';
    this._RequiredValidator_77_4.check_required(currVal_77_1_0,throwOnChange,false);
    this._RequiredValidator_77_4.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_77_2_0:any = 'content';
    this._NgModel_77_7.check_name(currVal_77_2_0,throwOnChange,false);
    const currVal_77_2_1:any = this.context.message.Content;
    this._NgModel_77_7.check_model(currVal_77_2_1,throwOnChange,false);
    this._NgModel_77_7.ngDoCheck(this,this._el_77,throwOnChange);
    this._NgControlStatus_77_9.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_116:any = ('#myModal' + this.context.traverseItem.ID);
    if (import3.checkBinding(throwOnChange,this._expr_116,currVal_116)) {
      this.renderer.setElementAttribute(this._el_0,'data-target',((currVal_116 == null)? (null as any): currVal_116.toString()));
      this._expr_116 = currVal_116;
    }
    const currVal_117:any = import3.inlineInterpolate(1,'\n        ',this.context.traverseItem.Description,'\n    ');
    if (import3.checkBinding(throwOnChange,this._expr_117,currVal_117)) {
      this.renderer.setText(this._text_3,currVal_117);
      this._expr_117 = currVal_117;
    }
    const currVal_118:any = ('myModal' + this.context.traverseItem.ID);
    if (import3.checkBinding(throwOnChange,this._expr_118,currVal_118)) {
      this.renderer.setElementProperty(this._el_6,'id',currVal_118);
      this._expr_118 = currVal_118;
    }
    const currVal_119:any = import3.inlineInterpolate(1,'',this.context.traverseItem.Title,'');
    if (import3.checkBinding(throwOnChange,this._expr_119,currVal_119)) {
      this.renderer.setText(this._text_19,currVal_119);
      this._expr_119 = currVal_119;
    }
    const currVal_120:any = import3.inlineInterpolate(1,'\n                ',this.context.traverseItem.Text,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_120,currVal_120)) {
      this.renderer.setText(this._text_23,currVal_120);
      this._expr_120 = currVal_120;
    }
    const currVal_121:any = ('#collapseExample' + this.context.traverseItem.ID);
    if (import3.checkBinding(throwOnChange,this._expr_121,currVal_121)) {
      this.renderer.setElementAttribute(this._el_27,'href',((currVal_121 == null)? (null as any): currVal_121.toString()));
      this._expr_121 = currVal_121;
    }
    const currVal_122:any = ('collapseExample' + this.context.traverseItem.ID);
    if (import3.checkBinding(throwOnChange,this._expr_122,currVal_122)) {
      this.renderer.setElementAttribute(this._el_27,'aria-controls',((currVal_122 == null)? (null as any): currVal_122.toString()));
      this._expr_122 = currVal_122;
    }
    const currVal_123:any = (this.context.isCollapsed? 'glyphicon glyphicon-menu-up': 'glyphicon glyphicon-menu-down');
    if (import3.checkBinding(throwOnChange,this._expr_123,currVal_123)) {
      this.renderer.setElementProperty(this._el_29,'className',currVal_123);
      this._expr_123 = currVal_123;
    }
    const currVal_124:any = (this.context.isCollapsed? 'glyphicon glyphicon-menu-up': 'glyphicon glyphicon-menu-down');
    if (import3.checkBinding(throwOnChange,this._expr_124,currVal_124)) {
      this.renderer.setElementProperty(this._el_31,'className',currVal_124);
      this._expr_124 = currVal_124;
    }
    const currVal_125:any = ('collapseExample' + this.context.traverseItem.ID);
    if (import3.checkBinding(throwOnChange,this._expr_125,currVal_125)) {
      this.renderer.setElementProperty(this._el_36,'id',currVal_125);
      this._expr_125 = currVal_125;
    }
    this._NgControlStatusGroup_40_5.checkHost(this,this,this._el_40,throwOnChange);
    valUnwrapper.reset();
    const currVal_126:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,this._pipe_translate_0.transform)('Name')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_126,currVal_126))) {
      this.renderer.setText(this._text_45,currVal_126);
      this._expr_126 = currVal_126;
    }
    this._RequiredValidator_49_4.checkHost(this,this,this._el_49,throwOnChange);
    this._NgControlStatus_49_9.checkHost(this,this,this._el_49,throwOnChange);
    const currVal_129:any = (this._NgModel_49_7.context.valid || this._NgModel_49_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_129,currVal_129)) {
      this.renderer.setElementProperty(this._el_51,'hidden',currVal_129);
      this._expr_129 = currVal_129;
    }
    valUnwrapper.reset();
    const currVal_130:any = import3.inlineInterpolate(1,'\n                                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,this._pipe_translate_0.transform)('Name is required')),'\n                                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_130,currVal_130))) {
      this.renderer.setText(this._text_52,currVal_130);
      this._expr_130 = currVal_130;
    }
    valUnwrapper.reset();
    const currVal_132:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_2,this._pipe_translate_0.transform)('Email')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_132,currVal_132))) {
      this.renderer.setText(this._text_59,currVal_132);
      this._expr_132 = currVal_132;
    }
    this._RequiredValidator_63_4.checkHost(this,this,this._el_63,throwOnChange);
    this._NgControlStatus_63_9.checkHost(this,this,this._el_63,throwOnChange);
    const currVal_134:any = (this._NgModel_63_7.context.valid || this._NgModel_63_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_134,currVal_134)) {
      this.renderer.setElementProperty(this._el_65,'hidden',currVal_134);
      this._expr_134 = currVal_134;
    }
    valUnwrapper.reset();
    const currVal_135:any = import3.inlineInterpolate(1,'\n                                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_3,this._pipe_translate_0.transform)('Email is required')),'\n                                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_135,currVal_135))) {
      this.renderer.setText(this._text_66,currVal_135);
      this._expr_135 = currVal_135;
    }
    valUnwrapper.reset();
    const currVal_137:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_4,this._pipe_translate_0.transform)('Content')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_137,currVal_137))) {
      this.renderer.setText(this._text_73,currVal_137);
      this._expr_137 = currVal_137;
    }
    this._RequiredValidator_77_4.checkHost(this,this,this._el_77,throwOnChange);
    this._NgControlStatus_77_9.checkHost(this,this,this._el_77,throwOnChange);
    const currVal_139:any = (this._NgModel_77_7.context.valid || this._NgModel_77_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_139,currVal_139)) {
      this.renderer.setElementProperty(this._el_79,'hidden',currVal_139);
      this._expr_139 = currVal_139;
    }
    valUnwrapper.reset();
    const currVal_140:any = import3.inlineInterpolate(1,'\n                                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_5,this._pipe_translate_0.transform)('Content is required')),'\n                                ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_140,currVal_140))) {
      this.renderer.setText(this._text_80,currVal_140);
      this._expr_140 = currVal_140;
    }
    const currVal_142:boolean = !this._NgForm_40_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_142,currVal_142)) {
      this.renderer.setElementClass(this._el_84,'not-allowed',currVal_142);
      this._expr_142 = currVal_142;
    }
    const currVal_143:any = this._NgForm_40_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_143,currVal_143)) {
      this.renderer.setElementClass(this._el_84,'draw',currVal_143);
      this._expr_143 = currVal_143;
    }
    const currVal_144:boolean = !this._NgForm_40_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_144,currVal_144)) {
      this.renderer.setElementProperty(this._el_84,'disabled',currVal_144);
      this._expr_144 = currVal_144;
    }
    valUnwrapper.reset();
    const currVal_145:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_6,this._pipe_translate_0.transform)('Submit')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_145,currVal_145))) {
      this.renderer.setText(this._text_85,currVal_145);
      this._expr_145 = currVal_145;
    }
  }
  destroyInternal():void {
    this._NgModel_49_7.ngOnDestroy();
    this._NgModel_63_7.ngOnDestroy();
    this._NgModel_77_7.ngOnDestroy();
    this._NgForm_40_3.ngOnDestroy();
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      this.context.isCollapsed = !this.context.isCollapsed;
      const pd_sub_0:any = ((<any>this._NgForm_40_3.context.reset()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_40(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_40_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_49_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.person.Name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_63(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_63_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.person.Email = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_77(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_77_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.message.Content = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}