/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['@media (min-width: 992px) {\n  img[_ngcontent-%COMP%]:hover {\n    transform: scale(1.1);\n    transition: all 1s ease-out; }\n  img[_ngcontent-%COMP%] {\n    transition: all 1s ease-out;\n    transform: scale(1); }\n  .item-content[_ngcontent-%COMP%] {\n    height: 350px; } }\n\n.item-content[_ngcontent-%COMP%] {\n  overflow: hidden;\n  height: 350px;\n  background-color: black; }\n  .item-content--img[_ngcontent-%COMP%] {\n    width: 100%;\n    height: auto;\n    vertical-align: central;\n    cursor: pointer; }\n  .item-content--card-text[_ngcontent-%COMP%] {\n    overflow-y: scroll;\n    overflow-x: hidden;\n    padding-top: 25px;\n    padding-left: 25px;\n    padding-right: 25px;\n    background-color: aliceblue;\n    height: 100%; }\n  .item-content--toggle-state[_ngcontent-%COMP%] {\n    position: absolute;\n    z-index: 1;\n    cursor: pointer; }\n    .item-content--toggle-state--img[_ngcontent-%COMP%] {\n      cursor: pointer; }\n\n.item-wrp[_ngcontent-%COMP%] {\n  border-radius: 5px;\n  margin-top: 30px; }\n\n.item-caption[_ngcontent-%COMP%] {\n  background-color: black;\n  margin-top: 2px;\n  height: 35px; }'];