/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.fixed-button[_ngcontent-%COMP%] {\n  position: fixed;\n  bottom: 0;\n   }\n\n.non-footer-mode[_ngcontent-%COMP%] {\n  position: fixed;\n  bottom: 0; }\n\n.footer-mode[_ngcontent-%COMP%] {\n  position: absolute;\n  bottom: 100px; }\n\n.hebrew-mode[_ngcontent-%COMP%] {\n  left: 30px; }\n\n.english-mode[_ngcontent-%COMP%] {\n  right: 30px; }\n\ndiv[_ngcontent-%COMP%] {\n  \n   }\n\nbutton[_ngcontent-%COMP%] {\n  opacity: 0.5;\n  border-radius: 50% !important; }\n  button[_ngcontent-%COMP%]:hover {\n    opacity: 1; }'];