/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.main-wrp[_ngcontent-%COMP%] {\n  \n  z-index: 1;\n  color: white;\n  position: absolute;\n  top: 0;\n  direction: initial;\n  height: 50px; }\n  .main-wrp-ltr[_ngcontent-%COMP%] {\n    right: 0; }\n  .main-wrp-rtl[_ngcontent-%COMP%] {\n    left: 0; }\n  .main-wrp--lang-wrp-rtl[_ngcontent-%COMP%] {\n    float: left; }\n  .main-wrp--lang-wrp-ltr[_ngcontent-%COMP%] {\n    float: right; }\n\n@keyframes rotating {\n  from {\n    -webkit-transform: rotateY(0deg); }\n  to {\n    -webkit-transform: rotateY(180deg); } }\n\n@keyframes enlarge {\n  0% {\n    transform: scale(1); }\n  20% {\n    transform: scale(1.5); }\n  40% {\n    transform: scale(1); } }\n  .main-wrp--toggle-wrp[_ngcontent-%COMP%] {\n    height: 50px;\n    background-size: contain;\n    background-repeat: no-repeat;\n    width: 50px;\n    \n    \n    background-image: url("http://res.cloudinary.com/lior/image/upload/v1487411891/Rotating_globe_qhxrhh.gif");\n    \n    \n    \n    transition: transform .main-wrp--toggle-wrp --img;\n      transition-height: 50px;\n      transition-width: auto; }\n  .main-wrp--toggle-wrp-rtl[_ngcontent-%COMP%] {\n    float: right;\n     }\n  .main-wrp--toggle-wrp-ltr[_ngcontent-%COMP%] {\n    \n    float: left; }'];
//# sourceMappingURL=lang-bar.component.css.shim.ngstyle.js.map