/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.galilu-link[_ngcontent-%COMP%] {\n  opacity: 0.5;\n  border-radius: 50% !important; }\n  .galilu-link[_ngcontent-%COMP%]:hover {\n    opacity: 1; }'];