/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/services/services';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../app/services/page-name.service';
import * as import11 from './app.component.css.shim.ngstyle';
import * as import12 from '../../app/HeaderImage/header.image';
import * as import13 from './HeaderImage/header.image.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import16 from '../../app/pipes/pipes';
import * as import17 from '@angular/core/src/change_detection/change_detection_util';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import8.CacheManager,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injector(0),this.injectorGet(import10.pageNameService,this.parentIndex),this.injectorGet(import8.youTubeService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AppComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import11.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import12.HeaderImage>;
  _HeaderImage_4_3:import13.Wrapper_HeaderImage;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _vc_10:import14.ViewContainer;
  _RouterOutlet_10_5:import15.Wrapper_RouterOutlet;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  _pipe_translate_0:import16.TranslatePipe;
  _pipe_translate_0_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_74 = import17.UNINITIALIZED;
    this._expr_75 = import17.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'header-image',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import13.View_HeaderImage0(this.viewUtils,this,4,this._el_4);
    this._HeaderImage_4_3 = new import13.Wrapper_HeaderImage(this.parentView.injectorGet(import10.pageNameService,this.parentIndex),this.parentView.injectorGet(import8.DataService,this.parentIndex),this.parentView.injectorGet(import8.LogService,this.parentIndex),this.parentView.injectorGet(import18.DomSanitizer,this.parentIndex),this.parentView.injectorGet(import9.Router,this.parentIndex));
    this._text_5 = this.renderer.createText((null as any),'        \n        ',(null as any));
    this.compView_4.create(this._HeaderImage_4_3.context);
    this._text_6 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n\n\n\n\n\n\n\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_10 = new import14.ViewContainer(10,8,this,this._el_10);
    this._RouterOutlet_10_5 = new import15.Wrapper_RouterOutlet(this.parentView.injectorGet(import19.RouterOutletMap,this.parentIndex),this._vc_10.vcRef,this.parentView.injectorGet(import20.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n\n\n    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'footer',new import3.InlineArray2(2,'id','footer'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row footer-row text-center'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'a',new import3.InlineArray4(4,'class','h5','href','mailto:noyaschleien@gmail.com'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'noyaschleien@gmail.com',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-sm-7'),(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-2'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_17,'hr',new import3.InlineArray2(2,'class','dl-horizontal'),(null as any));
    this._text_34 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-sm-12 hidden-xs'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Noya Schleien@2013',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'|',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_35,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Developed by',(null as any));
    this._text_45 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_35,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Future WebSites',(null as any));
    this._text_48 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_49 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Noya Schleien@2013',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n                    ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Developed by',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,'\n                    ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_56,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Future WebSites',(null as any));
    this._text_63 = this.renderer.createText(this._el_56,'\n                ',(null as any));
    this._text_64 = this.renderer.createText(this._el_17,'\n\n            ',(null as any));
    this._text_65 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_66 = this.renderer.createText(this._el_13,'\n\n\n\n\n    ',(null as any));
    this._text_67 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_68 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_29));
    this._pipe_translate_0 = new import16.TranslatePipe(this.parentView.injectorGet(import8.TranslationService,this.parentIndex),this.parentView.injectorGet(import8.CacheManager,this.parentIndex));
    this._pipe_translate_0_0 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.HeaderImage) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._HeaderImage_4_3.context; }
    if (((token === import21.RouterOutlet) && (10 === requestNodeIndex))) { return this._RouterOutlet_10_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import17.ValueUnwrapper();
    const currVal_4_0_0:any = 'home';
    this._HeaderImage_4_3.check_pageName(currVal_4_0_0,throwOnChange,false);
    this._HeaderImage_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._RouterOutlet_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
    const currVal_74:any = this.context.dir;
    if (import3.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementProperty(this._el_0,'dir',currVal_74);
      this._expr_74 = currVal_74;
    }
    valUnwrapper.reset();
    const currVal_75:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,this._pipe_translate_0.transform)('Order Concert')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_75,currVal_75))) {
      this.renderer.setText(this._text_30,currVal_75);
      this._expr_75 = currVal_75;
    }
    this.compView_4.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_10.destroyNestedViews();
    this.compView_4.destroy();
    this._RouterOutlet_10_5.ngOnDestroy();
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.goToContact()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}