/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/services/services';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../app/services/page-name.service';
import * as import11 from './app.component.css.shim.ngstyle';
import * as import12 from '../../app/HeaderImage/header.image';
import * as import13 from './HeaderImage/header.image.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import17 from '../../app/pipes/pipes';
import * as import18 from '@angular/core/src/change_detection/change_detection_util';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/router/src/router_outlet_map';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from '@angular/router/src/directives/router_outlet';
import * as import25 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import26 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import27 from '@angular/core/src/linker/query_list';
import * as import28 from '@angular/router/src/router_state';
import * as import29 from '@angular/common/src/location/location_strategy';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from '@angular/router/src/directives/router_link';
import * as import32 from '@angular/router/src/directives/router_link_active';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import8.CacheManager,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injector(0),this.injectorGet(import10.pageNameService,this.parentIndex),this.injectorGet(import8.youTubeService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AppComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import11.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import12.HeaderImage>;
  _HeaderImage_4_3:import13.Wrapper_HeaderImage;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import14.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import15.Wrapper_NgIf;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _vc_27:import14.ViewContainer;
  _RouterOutlet_27_5:import16.Wrapper_RouterOutlet;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  /*private*/ _expr_94:any;
  /*private*/ _expr_95:any;
  /*private*/ _expr_96:any;
  _pipe_translate_0:import17.TranslatePipe;
  /*private*/ _expr_98:any;
  _pipe_translate_0_17:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_94 = import18.UNINITIALIZED;
    this._expr_95 = import18.UNINITIALIZED;
    this._expr_96 = import18.UNINITIALIZED;
    this._expr_98 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'header-image',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import13.View_HeaderImage0(this.viewUtils,this,4,this._el_4);
    this._HeaderImage_4_3 = new import13.Wrapper_HeaderImage(this.parentView.injectorGet(import10.pageNameService,this.parentIndex),this.parentView.injectorGet(import8.DataService,this.parentIndex),this.parentView.injectorGet(import8.LogService,this.parentIndex),this.parentView.injectorGet(import19.DomSanitizer,this.parentIndex),this.parentView.injectorGet(import9.Router,this.parentIndex));
    this.compView_4.create(this._HeaderImage_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row container-fluid-margin'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','btn-group-sm'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray4(4,'class','langLinks','type','button'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Eng',(null as any));
    this._text_15 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray4(4,'class','langLinks','type','button'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'עבר',(null as any));
    this._text_18 = this.renderer.createText(this._el_10,'\n\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_23 = new import14.ViewContainer(23,0,this,this._anchor_23);
    this._TemplateRef_23_5 = new import20.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import15.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_0,'\n\n\n\n\n\n\n    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_27 = new import14.ViewContainer(27,25,this,this._el_27);
    this._RouterOutlet_27_5 = new import16.Wrapper_RouterOutlet(this.parentView.injectorGet(import21.RouterOutletMap,this.parentIndex),this._vc_27.vcRef,this.parentView.injectorGet(import22.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_28 = this.renderer.createText(this._el_25,'\n\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n\n\n\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_0,'footer',new import3.InlineArray2(2,'id','footer'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','row footer-row text-center'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'a',new import3.InlineArray4(4,'class','h5','href','mailto:noyaschleien@gmail.com'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'noyaschleien@gmail.com',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._text_41 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-sm-7'),(null as any));
    this._text_43 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-2'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n                    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_44,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'',(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._text_49 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_34,'hr',new import3.InlineArray2(2,'class','dl-horizontal'),(null as any));
    this._text_51 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-sm-12 hidden-xs'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                    ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Noya Schleien@2013',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n                    ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_52,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'|',(null as any));
    this._text_59 = this.renderer.createText(this._el_52,'\n                    ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_52,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'Developed by',(null as any));
    this._text_62 = this.renderer.createText(this._el_52,'\n                    ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_52,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Future WebSites',(null as any));
    this._text_65 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._text_66 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n                    ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Noya Schleien@2013',(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n                ',(null as any));
    this._text_72 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n                    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'Developed by',(null as any));
    this._text_77 = this.renderer.createText(this._el_73,'\n                    ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_73,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'Future WebSites',(null as any));
    this._text_80 = this.renderer.createText(this._el_73,'\n                ',(null as any));
    this._text_81 = this.renderer.createText(this._el_34,'\n\n            ',(null as any));
    this._text_82 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_83 = this.renderer.createText(this._el_30,'\n\n\n\n\n    ',(null as any));
    this._text_84 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_85 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_86 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    this._pipe_translate_0 = new import17.TranslatePipe(this.parentView.injectorGet(import8.TranslationService,this.parentIndex),this.parentView.injectorGet(import8.CacheManager,this.parentIndex));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_46,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_46));
    this._pipe_translate_0_17 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._text_86
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.HeaderImage) && (4 === requestNodeIndex))) { return this._HeaderImage_4_3.context; }
    if (((token === import20.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import23.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import24.RouterOutlet) && (27 === requestNodeIndex))) { return this._RouterOutlet_27_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_4_0_0:any = 'home';
    this._HeaderImage_4_3.check_pageName(currVal_4_0_0,throwOnChange,false);
    this._HeaderImage_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_23_0_0:any = this.context.displayMenu;
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    this._RouterOutlet_27_5.ngDoCheck(this,this._el_27,throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    const currVal_94:any = this.context.dir;
    if (import3.checkBinding(throwOnChange,this._expr_94,currVal_94)) {
      this.renderer.setElementProperty(this._el_0,'dir',currVal_94);
      this._expr_94 = currVal_94;
    }
    const currVal_95:any = this.context.isHebrew;
    if (import3.checkBinding(throwOnChange,this._expr_95,currVal_95)) {
      this.renderer.setElementClass(this._el_8,'text-left',currVal_95);
      this._expr_95 = currVal_95;
    }
    const currVal_96:boolean = !this.context.isHebrew;
    if (import3.checkBinding(throwOnChange,this._expr_96,currVal_96)) {
      this.renderer.setElementClass(this._el_8,'text-right',currVal_96);
      this._expr_96 = currVal_96;
    }
    valUnwrapper.reset();
    const currVal_98:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_17,this._pipe_translate_0.transform)('Order Concert')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_98,currVal_98))) {
      this.renderer.setText(this._text_47,currVal_98);
      this._expr_98 = currVal_98;
    }
    this.compView_4.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_23.destroyNestedViews();
    this._vc_27.destroyNestedViews();
    this.compView_4.destroy();
    this._RouterOutlet_27_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 23)) { return new View_AppComponent1(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    return (null as any);
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeToEnglish()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeToHebrew()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_46(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.goToContact()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _RouterLinkWithHref_29_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_29_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_29_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_29_1:import27.QueryList<any>;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _RouterLinkWithHref_32_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_32_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_32_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_32_1:import27.QueryList<any>;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _RouterLinkWithHref_38_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_38_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_38_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_38_1:import27.QueryList<any>;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _RouterLinkWithHref_41_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_41_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_41_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_41_1:import27.QueryList<any>;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _RouterLinkWithHref_47_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_47_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_47_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_47_1:import27.QueryList<any>;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _RouterLinkWithHref_50_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_50_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_50_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_50_1:import27.QueryList<any>;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _RouterLinkWithHref_56_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_56_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_56_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_56_1:import27.QueryList<any>;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _RouterLinkWithHref_59_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_59_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_59_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_59_1:import27.QueryList<any>;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _RouterLinkWithHref_65_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_65_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_65_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_65_1:import27.QueryList<any>;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _RouterLinkWithHref_68_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_68_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_68_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_68_1:import27.QueryList<any>;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _RouterLinkWithHref_74_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_74_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_74_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_74_1:import27.QueryList<any>;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _RouterLinkWithHref_77_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_77_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_77_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_77_1:import27.QueryList<any>;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _RouterLinkWithHref_83_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_83_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_83_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_83_1:import27.QueryList<any>;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _RouterLinkWithHref_86_3:import25.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_86_4:import26.Wrapper_RouterLinkActive;
  _query_RouterLink_86_0:import27.QueryList<any>;
  _query_RouterLinkWithHref_86_1:import27.QueryList<any>;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  /*private*/ _expr_148:any;
  /*private*/ _expr_149:any;
  _pipe_translate_0_0:any;
  /*private*/ _expr_151:any;
  _pipe_translate_0_1:any;
  /*private*/ _expr_153:any;
  _pipe_translate_0_2:any;
  _arr_155:any;
  /*private*/ _expr_156:any;
  _pipe_translate_0_3:any;
  _arr_158:any;
  /*private*/ _expr_159:any;
  _pipe_translate_0_4:any;
  _arr_161:any;
  /*private*/ _expr_162:any;
  _pipe_translate_0_5:any;
  _arr_164:any;
  /*private*/ _expr_165:any;
  _pipe_translate_0_6:any;
  _arr_167:any;
  /*private*/ _expr_168:any;
  _pipe_translate_0_7:any;
  _arr_170:any;
  /*private*/ _expr_171:any;
  _pipe_translate_0_8:any;
  _arr_173:any;
  /*private*/ _expr_174:any;
  _pipe_translate_0_9:any;
  _arr_176:any;
  /*private*/ _expr_177:any;
  _pipe_translate_0_10:any;
  _arr_179:any;
  /*private*/ _expr_180:any;
  _pipe_translate_0_11:any;
  _arr_182:any;
  /*private*/ _expr_183:any;
  _pipe_translate_0_12:any;
  _arr_185:any;
  /*private*/ _expr_186:any;
  _pipe_translate_0_13:any;
  _arr_188:any;
  /*private*/ _expr_189:any;
  _pipe_translate_0_14:any;
  _arr_191:any;
  /*private*/ _expr_192:any;
  _pipe_translate_0_15:any;
  _arr_194:any;
  /*private*/ _expr_195:any;
  _pipe_translate_0_16:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_148 = import18.UNINITIALIZED;
    this._expr_149 = import18.UNINITIALIZED;
    this._expr_151 = import18.UNINITIALIZED;
    this._expr_153 = import18.UNINITIALIZED;
    this._arr_155 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_156 = import18.UNINITIALIZED;
    this._arr_158 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_159 = import18.UNINITIALIZED;
    this._arr_161 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_162 = import18.UNINITIALIZED;
    this._arr_164 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_165 = import18.UNINITIALIZED;
    this._arr_167 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_168 = import18.UNINITIALIZED;
    this._arr_170 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_171 = import18.UNINITIALIZED;
    this._arr_173 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_174 = import18.UNINITIALIZED;
    this._arr_176 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_177 = import18.UNINITIALIZED;
    this._arr_179 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_180 = import18.UNINITIALIZED;
    this._arr_182 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_183 = import18.UNINITIALIZED;
    this._arr_185 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_186 = import18.UNINITIALIZED;
    this._arr_188 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_189 = import18.UNINITIALIZED;
    this._arr_191 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_192 = import18.UNINITIALIZED;
    this._arr_194 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_195 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','navbar navbar-default my-navbar','style',''),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray8(8,'class','navbar-toggle','data-target','.navbar-collapse','data-toggle','collapse','type','button'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'style','font-weight: 900; color: white'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'h4',new import3.InlineArray2(2,'class','navMenu hidden-lg hidden-md hidden-sm mobliePath'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','white-font'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','white-font'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'|',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','pageName white-font'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_10,'\n\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','navbar-collapse collapse'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'ul',new import3.InlineArray2(2,'class','menu-ul nav nav-pills nav-justified '),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_29_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_29_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_29),this.renderer);
    this._query_RouterLink_29_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_29_1 = new import27.QueryList<any>();
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_32_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_32_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_32),this.renderer);
    this._query_RouterLink_32_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_32_1 = new import27.QueryList<any>();
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_35 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_38_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_38_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_38),this.renderer);
    this._query_RouterLink_38_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_38_1 = new import27.QueryList<any>();
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_36,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_41_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_41_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_41),this.renderer);
    this._query_RouterLink_41_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_41_1 = new import27.QueryList<any>();
    this._text_42 = this.renderer.createText(this._el_41,'',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_47_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_47_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_47),this.renderer);
    this._query_RouterLink_47_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_47_1 = new import27.QueryList<any>();
    this._text_48 = this.renderer.createText(this._el_47,'',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_45,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_50_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_50_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_50),this.renderer);
    this._query_RouterLink_50_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_50_1 = new import27.QueryList<any>();
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    this._text_52 = this.renderer.createText(this._el_45,'\n\n                ',(null as any));
    this._text_53 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_56_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_56_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_56),this.renderer);
    this._query_RouterLink_56_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_56_1 = new import27.QueryList<any>();
    this._text_57 = this.renderer.createText(this._el_56,'',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_54,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_59_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_59_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_59),this.renderer);
    this._query_RouterLink_59_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_59_1 = new import27.QueryList<any>();
    this._text_60 = this.renderer.createText(this._el_59,'',(null as any));
    this._text_61 = this.renderer.createText(this._el_54,'\n\n                ',(null as any));
    this._text_62 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n                    ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_65_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_65_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_65),this.renderer);
    this._query_RouterLink_65_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_65_1 = new import27.QueryList<any>();
    this._text_66 = this.renderer.createText(this._el_65,'',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n                    ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_63,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_68_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_68_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_68),this.renderer);
    this._query_RouterLink_68_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_68_1 = new import27.QueryList<any>();
    this._text_69 = this.renderer.createText(this._el_68,'',(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n\n                ',(null as any));
    this._text_71 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n                    ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_74_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_74_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_74),this.renderer);
    this._query_RouterLink_74_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_74_1 = new import27.QueryList<any>();
    this._text_75 = this.renderer.createText(this._el_74,'',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n                    ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_72,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_77_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_77_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_77),this.renderer);
    this._query_RouterLink_77_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_77_1 = new import27.QueryList<any>();
    this._text_78 = this.renderer.createText(this._el_77,'',(null as any));
    this._text_79 = this.renderer.createText(this._el_72,'\n\n                ',(null as any));
    this._text_80 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n                    ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_81,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_83_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_83_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_83),this.renderer);
    this._query_RouterLink_83_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_83_1 = new import27.QueryList<any>();
    this._text_84 = this.renderer.createText(this._el_83,'',(null as any));
    this._text_85 = this.renderer.createText(this._el_81,'\n                    ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_81,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_86_3 = new import25.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import28.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import29.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_86_4 = new import26.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import30.ElementRef(this._el_86),this.renderer);
    this._query_RouterLink_86_0 = new import27.QueryList<any>();
    this._query_RouterLinkWithHref_86_1 = new import27.QueryList<any>();
    this._text_87 = this.renderer.createText(this._el_86,'',(null as any));
    this._text_88 = this.renderer.createText(this._el_81,'\n\n                ',(null as any));
    this._text_89 = this.renderer.createText(this._el_25,'\n\n\n            ',(null as any));
    this._text_90 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_91 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._pipe_translate_0_0 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this._pipe_translate_0_1 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this._pipe_translate_0_2 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_29));
    this._pipe_translate_0_3 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_32,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_32));
    this._pipe_translate_0_4 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    this._pipe_translate_0_5 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_41,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_41));
    this._pipe_translate_0_6 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_47));
    this._pipe_translate_0_7 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_50));
    this._pipe_translate_0_8 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_56));
    this._pipe_translate_0_9 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_59,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_59));
    this._pipe_translate_0_10 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_65,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_65));
    this._pipe_translate_0_11 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_68,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_68));
    this._pipe_translate_0_12 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_10:Function = import3.subscribeToRenderElement(this,this._el_74,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_74));
    this._pipe_translate_0_13 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_11:Function = import3.subscribeToRenderElement(this,this._el_77,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_77));
    this._pipe_translate_0_14 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_12:Function = import3.subscribeToRenderElement(this,this._el_83,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_83));
    this._pipe_translate_0_15 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    var disposable_13:Function = import3.subscribeToRenderElement(this,this._el_86,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_86));
    this._pipe_translate_0_16 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.RouterLinkWithHref) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._RouterLinkWithHref_29_3.context; }
    if (((token === import32.RouterLinkActive) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._RouterLinkActive_29_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkWithHref_32_3.context; }
    if (((token === import32.RouterLinkActive) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkActive_32_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLinkWithHref_38_3.context; }
    if (((token === import32.RouterLinkActive) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLinkActive_38_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RouterLinkWithHref_41_3.context; }
    if (((token === import32.RouterLinkActive) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RouterLinkActive_41_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._RouterLinkWithHref_47_3.context; }
    if (((token === import32.RouterLinkActive) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._RouterLinkActive_47_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._RouterLinkWithHref_50_3.context; }
    if (((token === import32.RouterLinkActive) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._RouterLinkActive_50_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._RouterLinkWithHref_56_3.context; }
    if (((token === import32.RouterLinkActive) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._RouterLinkActive_56_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._RouterLinkWithHref_59_3.context; }
    if (((token === import32.RouterLinkActive) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._RouterLinkActive_59_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._RouterLinkWithHref_65_3.context; }
    if (((token === import32.RouterLinkActive) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._RouterLinkActive_65_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._RouterLinkWithHref_68_3.context; }
    if (((token === import32.RouterLinkActive) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._RouterLinkActive_68_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._RouterLinkWithHref_74_3.context; }
    if (((token === import32.RouterLinkActive) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._RouterLinkActive_74_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._RouterLinkWithHref_77_3.context; }
    if (((token === import32.RouterLinkActive) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._RouterLinkActive_77_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._RouterLinkWithHref_83_3.context; }
    if (((token === import32.RouterLinkActive) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._RouterLinkActive_83_4.context; }
    if (((token === import31.RouterLinkWithHref) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 87)))) { return this._RouterLinkWithHref_86_3.context; }
    if (((token === import32.RouterLinkActive) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 87)))) { return this._RouterLinkActive_86_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_29_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_29_3.check_target(currVal_29_0_0,throwOnChange,false);
    const currVal_29_0_1:any = this._arr_155('home');
    this._RouterLinkWithHref_29_3.check_routerLink(currVal_29_0_1,throwOnChange,false);
    this._RouterLinkWithHref_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_29_1_0:any = 'active-menu-item';
    this._RouterLinkActive_29_4.check_routerLinkActive(currVal_29_1_0,throwOnChange,false);
    this._RouterLinkActive_29_4.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_32_0_0:any = this._arr_158('home');
    this._RouterLinkWithHref_32_3.check_routerLink(currVal_32_0_0,throwOnChange,false);
    this._RouterLinkWithHref_32_3.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_32_1_0:any = 'active-menu-item';
    this._RouterLinkActive_32_4.check_routerLinkActive(currVal_32_1_0,throwOnChange,false);
    this._RouterLinkActive_32_4.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_38_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_38_3.check_target(currVal_38_0_0,throwOnChange,false);
    const currVal_38_0_1:any = this._arr_161('biography');
    this._RouterLinkWithHref_38_3.check_routerLink(currVal_38_0_1,throwOnChange,false);
    this._RouterLinkWithHref_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_38_1_0:any = 'active-menu-item';
    this._RouterLinkActive_38_4.check_routerLinkActive(currVal_38_1_0,throwOnChange,false);
    this._RouterLinkActive_38_4.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_41_0_0:any = this._arr_164('biography');
    this._RouterLinkWithHref_41_3.check_routerLink(currVal_41_0_0,throwOnChange,false);
    this._RouterLinkWithHref_41_3.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_41_1_0:any = 'active-menu-item';
    this._RouterLinkActive_41_4.check_routerLinkActive(currVal_41_1_0,throwOnChange,false);
    this._RouterLinkActive_41_4.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_47_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_47_3.check_target(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = this._arr_167('pictures');
    this._RouterLinkWithHref_47_3.check_routerLink(currVal_47_0_1,throwOnChange,false);
    this._RouterLinkWithHref_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_47_1_0:any = 'active-menu-item';
    this._RouterLinkActive_47_4.check_routerLinkActive(currVal_47_1_0,throwOnChange,false);
    this._RouterLinkActive_47_4.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_50_0_0:any = this._arr_170('pictures');
    this._RouterLinkWithHref_50_3.check_routerLink(currVal_50_0_0,throwOnChange,false);
    this._RouterLinkWithHref_50_3.ngDoCheck(this,this._el_50,throwOnChange);
    const currVal_50_1_0:any = 'active-menu-item';
    this._RouterLinkActive_50_4.check_routerLinkActive(currVal_50_1_0,throwOnChange,false);
    this._RouterLinkActive_50_4.ngDoCheck(this,this._el_50,throwOnChange);
    const currVal_56_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_56_3.check_target(currVal_56_0_0,throwOnChange,false);
    const currVal_56_0_1:any = this._arr_173('videos');
    this._RouterLinkWithHref_56_3.check_routerLink(currVal_56_0_1,throwOnChange,false);
    this._RouterLinkWithHref_56_3.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_56_1_0:any = 'active-menu-item';
    this._RouterLinkActive_56_4.check_routerLinkActive(currVal_56_1_0,throwOnChange,false);
    this._RouterLinkActive_56_4.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_59_0_0:any = this._arr_176('videos');
    this._RouterLinkWithHref_59_3.check_routerLink(currVal_59_0_0,throwOnChange,false);
    this._RouterLinkWithHref_59_3.ngDoCheck(this,this._el_59,throwOnChange);
    const currVal_59_1_0:any = 'active-menu-item';
    this._RouterLinkActive_59_4.check_routerLinkActive(currVal_59_1_0,throwOnChange,false);
    this._RouterLinkActive_59_4.ngDoCheck(this,this._el_59,throwOnChange);
    const currVal_65_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_65_3.check_target(currVal_65_0_0,throwOnChange,false);
    const currVal_65_0_1:any = this._arr_179('programs');
    this._RouterLinkWithHref_65_3.check_routerLink(currVal_65_0_1,throwOnChange,false);
    this._RouterLinkWithHref_65_3.ngDoCheck(this,this._el_65,throwOnChange);
    const currVal_65_1_0:any = 'active-menu-item';
    this._RouterLinkActive_65_4.check_routerLinkActive(currVal_65_1_0,throwOnChange,false);
    this._RouterLinkActive_65_4.ngDoCheck(this,this._el_65,throwOnChange);
    const currVal_68_0_0:any = this._arr_182('programs');
    this._RouterLinkWithHref_68_3.check_routerLink(currVal_68_0_0,throwOnChange,false);
    this._RouterLinkWithHref_68_3.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_68_1_0:any = 'active-menu-item';
    this._RouterLinkActive_68_4.check_routerLinkActive(currVal_68_1_0,throwOnChange,false);
    this._RouterLinkActive_68_4.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_74_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_74_3.check_target(currVal_74_0_0,throwOnChange,false);
    const currVal_74_0_1:any = this._arr_185('links');
    this._RouterLinkWithHref_74_3.check_routerLink(currVal_74_0_1,throwOnChange,false);
    this._RouterLinkWithHref_74_3.ngDoCheck(this,this._el_74,throwOnChange);
    const currVal_74_1_0:any = 'active-menu-item';
    this._RouterLinkActive_74_4.check_routerLinkActive(currVal_74_1_0,throwOnChange,false);
    this._RouterLinkActive_74_4.ngDoCheck(this,this._el_74,throwOnChange);
    const currVal_77_0_0:any = this._arr_188('links');
    this._RouterLinkWithHref_77_3.check_routerLink(currVal_77_0_0,throwOnChange,false);
    this._RouterLinkWithHref_77_3.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_77_1_0:any = 'active-menu-item';
    this._RouterLinkActive_77_4.check_routerLinkActive(currVal_77_1_0,throwOnChange,false);
    this._RouterLinkActive_77_4.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_83_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_83_3.check_target(currVal_83_0_0,throwOnChange,false);
    const currVal_83_0_1:any = this._arr_191('contact');
    this._RouterLinkWithHref_83_3.check_routerLink(currVal_83_0_1,throwOnChange,false);
    this._RouterLinkWithHref_83_3.ngDoCheck(this,this._el_83,throwOnChange);
    const currVal_83_1_0:any = 'active-menu-item';
    this._RouterLinkActive_83_4.check_routerLinkActive(currVal_83_1_0,throwOnChange,false);
    this._RouterLinkActive_83_4.ngDoCheck(this,this._el_83,throwOnChange);
    const currVal_86_0_0:any = this._arr_194('contact');
    this._RouterLinkWithHref_86_3.check_routerLink(currVal_86_0_0,throwOnChange,false);
    this._RouterLinkWithHref_86_3.ngDoCheck(this,this._el_86,throwOnChange);
    const currVal_86_1_0:any = 'active-menu-item';
    this._RouterLinkActive_86_4.check_routerLinkActive(currVal_86_1_0,throwOnChange,false);
    this._RouterLinkActive_86_4.ngDoCheck(this,this._el_86,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_29_0.dirty) {
        this._query_RouterLink_29_0.reset(([] as any[]));
        this._RouterLinkActive_29_4.context.links = this._query_RouterLink_29_0;
        this._query_RouterLink_29_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_29_1.dirty) {
        this._query_RouterLinkWithHref_29_1.reset([this._RouterLinkWithHref_29_3.context]);
        this._RouterLinkActive_29_4.context.linksWithHrefs = this._query_RouterLinkWithHref_29_1;
        this._query_RouterLinkWithHref_29_1.notifyOnChanges();
      }
      if (this._query_RouterLink_32_0.dirty) {
        this._query_RouterLink_32_0.reset(([] as any[]));
        this._RouterLinkActive_32_4.context.links = this._query_RouterLink_32_0;
        this._query_RouterLink_32_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_32_1.dirty) {
        this._query_RouterLinkWithHref_32_1.reset([this._RouterLinkWithHref_32_3.context]);
        this._RouterLinkActive_32_4.context.linksWithHrefs = this._query_RouterLinkWithHref_32_1;
        this._query_RouterLinkWithHref_32_1.notifyOnChanges();
      }
      if (this._query_RouterLink_38_0.dirty) {
        this._query_RouterLink_38_0.reset(([] as any[]));
        this._RouterLinkActive_38_4.context.links = this._query_RouterLink_38_0;
        this._query_RouterLink_38_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_38_1.dirty) {
        this._query_RouterLinkWithHref_38_1.reset([this._RouterLinkWithHref_38_3.context]);
        this._RouterLinkActive_38_4.context.linksWithHrefs = this._query_RouterLinkWithHref_38_1;
        this._query_RouterLinkWithHref_38_1.notifyOnChanges();
      }
      if (this._query_RouterLink_41_0.dirty) {
        this._query_RouterLink_41_0.reset(([] as any[]));
        this._RouterLinkActive_41_4.context.links = this._query_RouterLink_41_0;
        this._query_RouterLink_41_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_41_1.dirty) {
        this._query_RouterLinkWithHref_41_1.reset([this._RouterLinkWithHref_41_3.context]);
        this._RouterLinkActive_41_4.context.linksWithHrefs = this._query_RouterLinkWithHref_41_1;
        this._query_RouterLinkWithHref_41_1.notifyOnChanges();
      }
      if (this._query_RouterLink_47_0.dirty) {
        this._query_RouterLink_47_0.reset(([] as any[]));
        this._RouterLinkActive_47_4.context.links = this._query_RouterLink_47_0;
        this._query_RouterLink_47_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_47_1.dirty) {
        this._query_RouterLinkWithHref_47_1.reset([this._RouterLinkWithHref_47_3.context]);
        this._RouterLinkActive_47_4.context.linksWithHrefs = this._query_RouterLinkWithHref_47_1;
        this._query_RouterLinkWithHref_47_1.notifyOnChanges();
      }
      if (this._query_RouterLink_50_0.dirty) {
        this._query_RouterLink_50_0.reset(([] as any[]));
        this._RouterLinkActive_50_4.context.links = this._query_RouterLink_50_0;
        this._query_RouterLink_50_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_50_1.dirty) {
        this._query_RouterLinkWithHref_50_1.reset([this._RouterLinkWithHref_50_3.context]);
        this._RouterLinkActive_50_4.context.linksWithHrefs = this._query_RouterLinkWithHref_50_1;
        this._query_RouterLinkWithHref_50_1.notifyOnChanges();
      }
      if (this._query_RouterLink_56_0.dirty) {
        this._query_RouterLink_56_0.reset(([] as any[]));
        this._RouterLinkActive_56_4.context.links = this._query_RouterLink_56_0;
        this._query_RouterLink_56_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_56_1.dirty) {
        this._query_RouterLinkWithHref_56_1.reset([this._RouterLinkWithHref_56_3.context]);
        this._RouterLinkActive_56_4.context.linksWithHrefs = this._query_RouterLinkWithHref_56_1;
        this._query_RouterLinkWithHref_56_1.notifyOnChanges();
      }
      if (this._query_RouterLink_59_0.dirty) {
        this._query_RouterLink_59_0.reset(([] as any[]));
        this._RouterLinkActive_59_4.context.links = this._query_RouterLink_59_0;
        this._query_RouterLink_59_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_59_1.dirty) {
        this._query_RouterLinkWithHref_59_1.reset([this._RouterLinkWithHref_59_3.context]);
        this._RouterLinkActive_59_4.context.linksWithHrefs = this._query_RouterLinkWithHref_59_1;
        this._query_RouterLinkWithHref_59_1.notifyOnChanges();
      }
      if (this._query_RouterLink_65_0.dirty) {
        this._query_RouterLink_65_0.reset(([] as any[]));
        this._RouterLinkActive_65_4.context.links = this._query_RouterLink_65_0;
        this._query_RouterLink_65_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_65_1.dirty) {
        this._query_RouterLinkWithHref_65_1.reset([this._RouterLinkWithHref_65_3.context]);
        this._RouterLinkActive_65_4.context.linksWithHrefs = this._query_RouterLinkWithHref_65_1;
        this._query_RouterLinkWithHref_65_1.notifyOnChanges();
      }
      if (this._query_RouterLink_68_0.dirty) {
        this._query_RouterLink_68_0.reset(([] as any[]));
        this._RouterLinkActive_68_4.context.links = this._query_RouterLink_68_0;
        this._query_RouterLink_68_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_68_1.dirty) {
        this._query_RouterLinkWithHref_68_1.reset([this._RouterLinkWithHref_68_3.context]);
        this._RouterLinkActive_68_4.context.linksWithHrefs = this._query_RouterLinkWithHref_68_1;
        this._query_RouterLinkWithHref_68_1.notifyOnChanges();
      }
      if (this._query_RouterLink_74_0.dirty) {
        this._query_RouterLink_74_0.reset(([] as any[]));
        this._RouterLinkActive_74_4.context.links = this._query_RouterLink_74_0;
        this._query_RouterLink_74_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_74_1.dirty) {
        this._query_RouterLinkWithHref_74_1.reset([this._RouterLinkWithHref_74_3.context]);
        this._RouterLinkActive_74_4.context.linksWithHrefs = this._query_RouterLinkWithHref_74_1;
        this._query_RouterLinkWithHref_74_1.notifyOnChanges();
      }
      if (this._query_RouterLink_77_0.dirty) {
        this._query_RouterLink_77_0.reset(([] as any[]));
        this._RouterLinkActive_77_4.context.links = this._query_RouterLink_77_0;
        this._query_RouterLink_77_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_77_1.dirty) {
        this._query_RouterLinkWithHref_77_1.reset([this._RouterLinkWithHref_77_3.context]);
        this._RouterLinkActive_77_4.context.linksWithHrefs = this._query_RouterLinkWithHref_77_1;
        this._query_RouterLinkWithHref_77_1.notifyOnChanges();
      }
      if (this._query_RouterLink_83_0.dirty) {
        this._query_RouterLink_83_0.reset(([] as any[]));
        this._RouterLinkActive_83_4.context.links = this._query_RouterLink_83_0;
        this._query_RouterLink_83_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_83_1.dirty) {
        this._query_RouterLinkWithHref_83_1.reset([this._RouterLinkWithHref_83_3.context]);
        this._RouterLinkActive_83_4.context.linksWithHrefs = this._query_RouterLinkWithHref_83_1;
        this._query_RouterLinkWithHref_83_1.notifyOnChanges();
      }
      if (this._query_RouterLink_86_0.dirty) {
        this._query_RouterLink_86_0.reset(([] as any[]));
        this._RouterLinkActive_86_4.context.links = this._query_RouterLink_86_0;
        this._query_RouterLink_86_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_86_1.dirty) {
        this._query_RouterLinkWithHref_86_1.reset([this._RouterLinkWithHref_86_3.context]);
        this._RouterLinkActive_86_4.context.linksWithHrefs = this._query_RouterLinkWithHref_86_1;
        this._query_RouterLinkWithHref_86_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_29_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_32_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_38_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_41_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_47_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_56_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_59_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_65_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_68_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_74_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_77_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_83_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_86_4.context.ngAfterContentInit(); }
    }
    const currVal_148:any = this.parentView.context.dir;
    if (import3.checkBinding(throwOnChange,this._expr_148,currVal_148)) {
      this.renderer.setElementProperty(this._el_0,'dir',currVal_148);
      this._expr_148 = currVal_148;
    }
    valUnwrapper.reset();
    const currVal_149:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Menu')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_149,currVal_149))) {
      this.renderer.setText(this._text_7,currVal_149);
      this._expr_149 = currVal_149;
    }
    valUnwrapper.reset();
    const currVal_151:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Noya Schleien')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_151,currVal_151))) {
      this.renderer.setText(this._text_13,currVal_151);
      this._expr_151 = currVal_151;
    }
    valUnwrapper.reset();
    const currVal_153:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_2,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)(this.parentView.context.pageName)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_153,currVal_153))) {
      this.renderer.setText(this._text_19,currVal_153);
      this._expr_153 = currVal_153;
    }
    this._RouterLinkWithHref_29_3.checkHost(this,this,this._el_29,throwOnChange);
    valUnwrapper.reset();
    const currVal_156:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_3,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Home')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_156,currVal_156))) {
      this.renderer.setText(this._text_30,currVal_156);
      this._expr_156 = currVal_156;
    }
    this._RouterLinkWithHref_32_3.checkHost(this,this,this._el_32,throwOnChange);
    valUnwrapper.reset();
    const currVal_159:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_4,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Home')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_159,currVal_159))) {
      this.renderer.setText(this._text_33,currVal_159);
      this._expr_159 = currVal_159;
    }
    this._RouterLinkWithHref_38_3.checkHost(this,this,this._el_38,throwOnChange);
    valUnwrapper.reset();
    const currVal_162:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_5,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Biography')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_162,currVal_162))) {
      this.renderer.setText(this._text_39,currVal_162);
      this._expr_162 = currVal_162;
    }
    this._RouterLinkWithHref_41_3.checkHost(this,this,this._el_41,throwOnChange);
    valUnwrapper.reset();
    const currVal_165:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_6,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Biography')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_165,currVal_165))) {
      this.renderer.setText(this._text_42,currVal_165);
      this._expr_165 = currVal_165;
    }
    this._RouterLinkWithHref_47_3.checkHost(this,this,this._el_47,throwOnChange);
    valUnwrapper.reset();
    const currVal_168:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_7,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Pictures')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_168,currVal_168))) {
      this.renderer.setText(this._text_48,currVal_168);
      this._expr_168 = currVal_168;
    }
    this._RouterLinkWithHref_50_3.checkHost(this,this,this._el_50,throwOnChange);
    valUnwrapper.reset();
    const currVal_171:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_8,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Pictures')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_171,currVal_171))) {
      this.renderer.setText(this._text_51,currVal_171);
      this._expr_171 = currVal_171;
    }
    this._RouterLinkWithHref_56_3.checkHost(this,this,this._el_56,throwOnChange);
    valUnwrapper.reset();
    const currVal_174:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_9,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Videos')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_174,currVal_174))) {
      this.renderer.setText(this._text_57,currVal_174);
      this._expr_174 = currVal_174;
    }
    this._RouterLinkWithHref_59_3.checkHost(this,this,this._el_59,throwOnChange);
    valUnwrapper.reset();
    const currVal_177:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_10,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Videos')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_177,currVal_177))) {
      this.renderer.setText(this._text_60,currVal_177);
      this._expr_177 = currVal_177;
    }
    this._RouterLinkWithHref_65_3.checkHost(this,this,this._el_65,throwOnChange);
    valUnwrapper.reset();
    const currVal_180:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_11,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Programs')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_180,currVal_180))) {
      this.renderer.setText(this._text_66,currVal_180);
      this._expr_180 = currVal_180;
    }
    this._RouterLinkWithHref_68_3.checkHost(this,this,this._el_68,throwOnChange);
    valUnwrapper.reset();
    const currVal_183:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_12,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Programs')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_183,currVal_183))) {
      this.renderer.setText(this._text_69,currVal_183);
      this._expr_183 = currVal_183;
    }
    this._RouterLinkWithHref_74_3.checkHost(this,this,this._el_74,throwOnChange);
    valUnwrapper.reset();
    const currVal_186:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_13,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Links')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_186,currVal_186))) {
      this.renderer.setText(this._text_75,currVal_186);
      this._expr_186 = currVal_186;
    }
    this._RouterLinkWithHref_77_3.checkHost(this,this,this._el_77,throwOnChange);
    valUnwrapper.reset();
    const currVal_189:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_14,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Links')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_189,currVal_189))) {
      this.renderer.setText(this._text_78,currVal_189);
      this._expr_189 = currVal_189;
    }
    this._RouterLinkWithHref_83_3.checkHost(this,this,this._el_83,throwOnChange);
    valUnwrapper.reset();
    const currVal_192:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_15,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Contact')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_192,currVal_192))) {
      this.renderer.setText(this._text_84,currVal_192);
      this._expr_192 = currVal_192;
    }
    this._RouterLinkWithHref_86_3.checkHost(this,this,this._el_86,throwOnChange);
    valUnwrapper.reset();
    const currVal_195:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_16,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Contact')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_195,currVal_195))) {
      this.renderer.setText(this._text_87,currVal_195);
      this._expr_195 = currVal_195;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_29_3.ngOnDestroy();
    this._RouterLinkActive_29_4.ngOnDestroy();
    this._RouterLinkWithHref_32_3.ngOnDestroy();
    this._RouterLinkActive_32_4.ngOnDestroy();
    this._RouterLinkWithHref_38_3.ngOnDestroy();
    this._RouterLinkActive_38_4.ngOnDestroy();
    this._RouterLinkWithHref_41_3.ngOnDestroy();
    this._RouterLinkActive_41_4.ngOnDestroy();
    this._RouterLinkWithHref_47_3.ngOnDestroy();
    this._RouterLinkActive_47_4.ngOnDestroy();
    this._RouterLinkWithHref_50_3.ngOnDestroy();
    this._RouterLinkActive_50_4.ngOnDestroy();
    this._RouterLinkWithHref_56_3.ngOnDestroy();
    this._RouterLinkActive_56_4.ngOnDestroy();
    this._RouterLinkWithHref_59_3.ngOnDestroy();
    this._RouterLinkActive_59_4.ngOnDestroy();
    this._RouterLinkWithHref_65_3.ngOnDestroy();
    this._RouterLinkActive_65_4.ngOnDestroy();
    this._RouterLinkWithHref_68_3.ngOnDestroy();
    this._RouterLinkActive_68_4.ngOnDestroy();
    this._RouterLinkWithHref_74_3.ngOnDestroy();
    this._RouterLinkActive_74_4.ngOnDestroy();
    this._RouterLinkWithHref_77_3.ngOnDestroy();
    this._RouterLinkActive_77_4.ngOnDestroy();
    this._RouterLinkWithHref_83_3.ngOnDestroy();
    this._RouterLinkActive_83_4.ngOnDestroy();
    this._RouterLinkWithHref_86_3.ngOnDestroy();
    this._RouterLinkActive_86_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_29_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_32(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_32_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_38_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_41(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_41_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_47_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_50_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_56_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_59(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_59_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_65(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_65_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_68(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_68_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_74(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_74_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_77(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_77_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_83(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_83_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_86(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_86_3.handleEvent(eventName,$event) && result);
    return result;
  }
}