/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.header[_ngcontent-%COMP%] {\n  background-color: #484444;\n  background-size: cover;\n  background-size: 100% 100%;\n  height: 300px;\n  height: 100vh; }'];