/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/HeaderImage/header.image';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../app/services/page-name.service';
import * as import10 from '../../../app/services/services';
import * as import11 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import12 from '@angular/router/src/router';
import * as import13 from './header.image.css.shim.ngstyle';
import * as import14 from '../../../app/LangBar/lang-bar.component';
import * as import15 from '../LangBar/lang-bar.component.ngfactory';
import * as import16 from '../../../app/Menu/menu';
import * as import17 from '../Menu/menu.ngfactory';
import * as import18 from '../../../app/pipes/pipes';
import * as import19 from '@angular/core/src/security';
export class Wrapper_HeaderImage {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderImage;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.HeaderImage(p0,p1,p2,p3,p4);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_pageName(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.pageName = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderImage_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderImage_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.HeaderImage>;
  _HeaderImage_0_3:Wrapper_HeaderImage;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderImage_Host0,renderType_HeaderImage_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'header-image',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderImage0(this.viewUtils,this,0,this._el_0);
    this._HeaderImage_0_3 = new Wrapper_HeaderImage(this.injectorGet(import9.pageNameService,this.parentIndex),this.injectorGet(import10.DataService,this.parentIndex),this.injectorGet(import10.LogService,this.parentIndex),this.injectorGet(import11.DomSanitizer,this.parentIndex),this.injectorGet(import12.Router,this.parentIndex));
    this.compView_0.create(this._HeaderImage_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._HeaderImage_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderImage) && (0 === requestNodeIndex))) { return this._HeaderImage_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderImage_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderImageNgFactory:import8.ComponentFactory<import0.HeaderImage> = new import8.ComponentFactory<import0.HeaderImage>('header-image',View_HeaderImage_Host0,import0.HeaderImage);
const styles_HeaderImage:any[] = [import13.styles];
var renderType_HeaderImage:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_HeaderImage,{});
export class View_HeaderImage0 extends import2.AppView<import0.HeaderImage> {
  _el_0:any;
  compView_0:import2.AppView<import14.LangBarComponent>;
  _LangBarComponent_0_3:import15.Wrapper_LangBarComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import2.AppView<import16.MenuComponent>;
  _MenuComponent_10_3:import17.Wrapper_MenuComponent;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  _pipe_translate_0:import18.TranslatePipe;
  _pipe_translate_0_0:any;
  /*private*/ _expr_21:any;
  _pipe_translate_0_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderImage0,renderType_HeaderImage,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_17 = import1.UNINITIALIZED;
    this._expr_18 = import1.UNINITIALIZED;
    this._expr_21 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'lang-bar',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_LangBarComponent0(this.viewUtils,this,0,this._el_0);
    this._LangBarComponent_0_3 = new import15.Wrapper_LangBarComponent(this.injector(0),this.parentView.injectorGet(import10.CacheManager,this.parentIndex));
    this.compView_0.create(this._LangBarComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','header row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','padding-top-15 rotator col-xs-12 h2'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','rotator col-xs-12 h2'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'main-menu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_10 = new import17.View_MenuComponent0(this.viewUtils,this,10,this._el_10);
    this._MenuComponent_10_3 = new import17.Wrapper_MenuComponent(this.parentView.injectorGet(import10.DataService,this.parentIndex),this.parentView.injectorGet(import10.CacheManager,this.parentIndex),this.parentView.injectorGet(import12.Router,this.parentIndex),this.injector(10),this.parentView.injectorGet(import9.pageNameService,this.parentIndex),this.parentView.injectorGet(import10.youTubeService,this.parentIndex));
    this.compView_10.create(this._MenuComponent_10_3.context);
    this._text_11 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._pipe_translate_0 = new import18.TranslatePipe(this.parentView.injectorGet(import10.TranslationService,this.parentIndex),this.parentView.injectorGet(import10.CacheManager,this.parentIndex));
    this._pipe_translate_0_0 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this._pipe_translate_0_1 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.LangBarComponent) && (0 === requestNodeIndex))) { return this._LangBarComponent_0_3.context; }
    if (((token === import16.MenuComponent) && (10 === requestNodeIndex))) { return this._MenuComponent_10_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this._LangBarComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._MenuComponent_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_17:any = this.context.safeImage;
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementStyle(this._el_2,'background-image',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_17) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_17).toString()));
      this._expr_17 = currVal_17;
    }
    valUnwrapper.reset();
    const currVal_18:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,this._pipe_translate_0.transform)(this.context.Title)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_18,currVal_18))) {
      this.renderer.setText(this._text_5,currVal_18);
      this._expr_18 = currVal_18;
    }
    valUnwrapper.reset();
    const currVal_21:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,this._pipe_translate_0.transform)(this.context.Subject)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_21,currVal_21))) {
      this.renderer.setText(this._text_8,currVal_21);
      this._expr_21 = currVal_21;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._MenuComponent_10_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_10.destroy();
  }
}